/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_7_oop.Panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import kelompok_7_oop.Kelas.AnggotaRuta;
import kelompok_7_oop.Kelas.Gangguan;
import kelompok_7_oop.Kelas.KarakteristikUmum;

/**
 *
 * @author Nashir
 */
public class KarakteristikUmumPanel extends javax.swing.JPanel {

    private JScrollPane mainScrollPane;
    private AnggotaRuta art;
    private KarakteristikUmum kU = new KarakteristikUmum();

    /**
     * Creates new form KarakteristikUmumPanel
     */
    public KarakteristikUmumPanel(JScrollPane mainScrollPane, AnggotaRuta art) {
        initComponents();
        this.mainScrollPane = mainScrollPane;
        this.art = art;
        ijazahComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ijazahComboBox.getSelectedIndex() <= 7) {
                    bidangStudiTextField.setEditable(false);
                }
            }
        });
    }

    private String getSelected(ButtonGroup bg) {
        for (Enumeration<AbstractButton> buttons = bg.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "tidak valid";
    }
    private Gangguan gangguan = new Gangguan();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelatihanKerjaButtonGroup = new javax.swing.ButtonGroup();
        penglihatanButtonGroup = new javax.swing.ButtonGroup();
        pendengaranButtonGroup = new javax.swing.ButtonGroup();
        mobilitasButtonGroup = new javax.swing.ButtonGroup();
        gerakanJariButtonGroup = new javax.swing.ButtonGroup();
        caraKomunikasiButtonGroup = new javax.swing.ButtonGroup();
        linnyaButtonGroup = new javax.swing.ButtonGroup();
        judulAPanel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ijazahComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        bidangStudiTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pelatihanKerjaPositifRadioButton = new javax.swing.JRadioButton();
        negatifPelatihanKerjaRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        kabKotaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kewarganegaraanTextField1 = new javax.swing.JTextField();
        provinsiTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tidakGangguanPenglihatanRadioButton = new javax.swing.JRadioButton();
        parahGangguanPenglihatanRadioButton = new javax.swing.JRadioButton();
        sedangGangguanPenglihatanRadioButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        parahGangguanPennglihatanRadioButton = new javax.swing.JRadioButton();
        sedangGangguanPendengaranRadioButton = new javax.swing.JRadioButton();
        tidakGangguanPendengaranRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tidakGangguanMobRadioButton = new javax.swing.JRadioButton();
        sedangGangguanMobRadioButton = new javax.swing.JRadioButton();
        parahGangguanMobRadioButton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tidakGangguanJariRadioButton = new javax.swing.JRadioButton();
        sedangGangguanJariRadioButton = new javax.swing.JRadioButton();
        parahGangguanJarRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        tidakGangguanKomRadioButton = new javax.swing.JRadioButton();
        sedangGangguanKomRadioButton = new javax.swing.JRadioButton();
        parahGangguanKomRadioButton = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        tidakGangguanLainnyaRadioButton = new javax.swing.JRadioButton();
        sedangGangguanRadioButton = new javax.swing.JRadioButton();
        parahGangguanLainnyaRadioButton = new javax.swing.JRadioButton();
        buttonNextPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        judulAPanel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judulAPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulAPanel.setText("V.A. KARAKTERISTIK UMUM");

        jLabel2.setText("1.a. Apakah ijazah STTB yang dimiliki (Nama)?");

        ijazahComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak punya ijazah SD", "Paket A", "SDLB", "SD/MI", "Paket B", "SMPLB", "SMP/MTs", "Paket C", "SMLB", "SMA/MA", "SMK/MAK", "Diploma I/II", "Diploma III", "Diploma IV/S1", "S2", "S3" }));
        ijazahComboBox.setSelectedIndex(-1);
        ijazahComboBox.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ijazahComboBoxComponentAdded(evt);
            }
        });

        jLabel3.setText("b. Jurusan pendidikan/bidang studi:");

        bidangStudiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidangStudiTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("c. Apakah (nama) pernah mendapat pelatihan kerja: ");

        pelatihanKerjaButtonGroup.add(pelatihanKerjaPositifRadioButton);
        pelatihanKerjaPositifRadioButton.setText("Ya");

        pelatihanKerjaButtonGroup.add(negatifPelatihanKerjaRadioButton);
        negatifPelatihanKerjaRadioButton.setText("Tidak");
        negatifPelatihanKerjaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifPelatihanKerjaRadioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("2. Kewarganegaraan (nama):");

        kabKotaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabKotaTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("3. Tempat tinggal (nama) lima tahun lalu:");

        kewarganegaraanTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kewarganegaraanTextField1ActionPerformed(evt);
            }
        });

        provinsiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinsiTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("4. Kesulitan/gangguan yang pernah dialami:");

        jLabel8.setText("a. Pengelihatan");

        penglihatanButtonGroup.add(tidakGangguanPenglihatanRadioButton);
        tidakGangguanPenglihatanRadioButton.setText("Tidak");

        penglihatanButtonGroup.add(parahGangguanPenglihatanRadioButton);
        parahGangguanPenglihatanRadioButton.setText("Parah");
        parahGangguanPenglihatanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parahGangguanPenglihatanRadioButtonActionPerformed(evt);
            }
        });

        penglihatanButtonGroup.add(sedangGangguanPenglihatanRadioButton);
        sedangGangguanPenglihatanRadioButton.setText("Sedang");
        sedangGangguanPenglihatanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedangGangguanPenglihatanRadioButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("b. Pendengaran");

        pendengaranButtonGroup.add(parahGangguanPennglihatanRadioButton);
        parahGangguanPennglihatanRadioButton.setText("Parah");
        parahGangguanPennglihatanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parahGangguanPennglihatanRadioButtonActionPerformed(evt);
            }
        });

        pendengaranButtonGroup.add(sedangGangguanPendengaranRadioButton);
        sedangGangguanPendengaranRadioButton.setText("Sedang");
        sedangGangguanPendengaranRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedangGangguanPendengaranRadioButtonActionPerformed(evt);
            }
        });

        pendengaranButtonGroup.add(tidakGangguanPendengaranRadioButton);
        tidakGangguanPendengaranRadioButton.setText("Tidak");

        jLabel10.setText("c. Mobilitas");

        mobilitasButtonGroup.add(tidakGangguanMobRadioButton);
        tidakGangguanMobRadioButton.setText("Tidak");

        mobilitasButtonGroup.add(sedangGangguanMobRadioButton);
        sedangGangguanMobRadioButton.setText("Sedang");
        sedangGangguanMobRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedangGangguanMobRadioButtonActionPerformed(evt);
            }
        });

        mobilitasButtonGroup.add(parahGangguanMobRadioButton);
        parahGangguanMobRadioButton.setText("Parah");
        parahGangguanMobRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parahGangguanMobRadioButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("d. Menggerakan Jari/Tangan");

        gerakanJariButtonGroup.add(tidakGangguanJariRadioButton);
        tidakGangguanJariRadioButton.setText("Tidak");

        gerakanJariButtonGroup.add(sedangGangguanJariRadioButton);
        sedangGangguanJariRadioButton.setText("Sedang");
        sedangGangguanJariRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedangGangguanJariRadioButtonActionPerformed(evt);
            }
        });

        gerakanJariButtonGroup.add(parahGangguanJarRadioButton);
        parahGangguanJarRadioButton.setText("Parah");
        parahGangguanJarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parahGangguanJarRadioButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("e. Berbicara/Berkomunikasi");

        caraKomunikasiButtonGroup.add(tidakGangguanKomRadioButton);
        tidakGangguanKomRadioButton.setText("Tidak");

        caraKomunikasiButtonGroup.add(sedangGangguanKomRadioButton);
        sedangGangguanKomRadioButton.setText("Sedang");
        sedangGangguanKomRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedangGangguanKomRadioButtonActionPerformed(evt);
            }
        });

        caraKomunikasiButtonGroup.add(parahGangguanKomRadioButton);
        parahGangguanKomRadioButton.setText("Parah");
        parahGangguanKomRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parahGangguanKomRadioButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("f. Mengingat, prilaku, dan lainnya");

        linnyaButtonGroup.add(tidakGangguanLainnyaRadioButton);
        tidakGangguanLainnyaRadioButton.setText("Tidak");
        tidakGangguanLainnyaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakGangguanLainnyaRadioButtonActionPerformed(evt);
            }
        });

        linnyaButtonGroup.add(sedangGangguanRadioButton);
        sedangGangguanRadioButton.setText("Sedang");
        sedangGangguanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedangGangguanRadioButtonActionPerformed(evt);
            }
        });

        linnyaButtonGroup.add(parahGangguanLainnyaRadioButton);
        parahGangguanLainnyaRadioButton.setText("Parah");
        parahGangguanLainnyaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parahGangguanLainnyaRadioButtonActionPerformed(evt);
            }
        });

        buttonNextPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextPanelMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nashir\\Desktop\\Next page_48px.png")); // NOI18N

        javax.swing.GroupLayout buttonNextPanelLayout = new javax.swing.GroupLayout(buttonNextPanel);
        buttonNextPanel.setLayout(buttonNextPanelLayout);
        buttonNextPanelLayout.setHorizontalGroup(
            buttonNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonNextPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        buttonNextPanelLayout.setVerticalGroup(
            buttonNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonNextPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(ijazahComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(pelatihanKerjaPositifRadioButton)
                                        .addGap(49, 49, 49)
                                        .addComponent(negatifPelatihanKerjaRadioButton))))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tidakGangguanMobRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sedangGangguanMobRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(parahGangguanMobRadioButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(108, 108, 108)
                                            .addComponent(tidakGangguanPendengaranRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sedangGangguanPendengaranRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(parahGangguanPennglihatanRadioButton))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(106, 106, 106)
                                            .addComponent(tidakGangguanPenglihatanRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sedangGangguanPenglihatanRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(parahGangguanPenglihatanRadioButton))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tidakGangguanJariRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sedangGangguanJariRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(parahGangguanJarRadioButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tidakGangguanKomRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sedangGangguanKomRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(parahGangguanKomRadioButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tidakGangguanLainnyaRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sedangGangguanRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(parahGangguanLainnyaRadioButton)))
                            .addComponent(jLabel8)))
                    .addComponent(judulAPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(bidangStudiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kabKotaTextField)
                                    .addComponent(provinsiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonNextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(kewarganegaraanTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(544, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulAPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ijazahComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinsiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bidangStudiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pelatihanKerjaPositifRadioButton)
                            .addComponent(negatifPelatihanKerjaRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tidakGangguanPenglihatanRadioButton)
                            .addComponent(sedangGangguanPenglihatanRadioButton)
                            .addComponent(parahGangguanPenglihatanRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tidakGangguanPendengaranRadioButton)
                            .addComponent(sedangGangguanPendengaranRadioButton)
                            .addComponent(parahGangguanPennglihatanRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tidakGangguanMobRadioButton)
                            .addComponent(sedangGangguanMobRadioButton)
                            .addComponent(parahGangguanMobRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tidakGangguanJariRadioButton)
                            .addComponent(sedangGangguanJariRadioButton)
                            .addComponent(parahGangguanJarRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tidakGangguanKomRadioButton)
                            .addComponent(sedangGangguanKomRadioButton)
                            .addComponent(parahGangguanKomRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tidakGangguanLainnyaRadioButton)
                            .addComponent(sedangGangguanRadioButton)
                            .addComponent(parahGangguanLainnyaRadioButton))))
                .addGap(19, 19, 19)
                .addComponent(buttonNextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(285, 285, 285)
                    .addComponent(kewarganegaraanTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(139, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ijazahComboBoxComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ijazahComboBoxComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ijazahComboBoxComponentAdded

    private void bidangStudiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidangStudiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidangStudiTextFieldActionPerformed

    private void negatifPelatihanKerjaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifPelatihanKerjaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifPelatihanKerjaRadioButtonActionPerformed

    private void kabKotaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabKotaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kabKotaTextFieldActionPerformed

    private void kewarganegaraanTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kewarganegaraanTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kewarganegaraanTextField1ActionPerformed

    private void provinsiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinsiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinsiTextFieldActionPerformed

    private void parahGangguanPenglihatanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parahGangguanPenglihatanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parahGangguanPenglihatanRadioButtonActionPerformed

    private void sedangGangguanPenglihatanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedangGangguanPenglihatanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedangGangguanPenglihatanRadioButtonActionPerformed

    private void parahGangguanPennglihatanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parahGangguanPennglihatanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parahGangguanPennglihatanRadioButtonActionPerformed

    private void sedangGangguanPendengaranRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedangGangguanPendengaranRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedangGangguanPendengaranRadioButtonActionPerformed

    private void sedangGangguanMobRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedangGangguanMobRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedangGangguanMobRadioButtonActionPerformed

    private void parahGangguanMobRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parahGangguanMobRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parahGangguanMobRadioButtonActionPerformed

    private void sedangGangguanJariRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedangGangguanJariRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedangGangguanJariRadioButtonActionPerformed

    private void parahGangguanJarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parahGangguanJarRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parahGangguanJarRadioButtonActionPerformed

    private void sedangGangguanKomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedangGangguanKomRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedangGangguanKomRadioButtonActionPerformed

    private void parahGangguanKomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parahGangguanKomRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parahGangguanKomRadioButtonActionPerformed

    private void sedangGangguanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedangGangguanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedangGangguanRadioButtonActionPerformed

    private void parahGangguanLainnyaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parahGangguanLainnyaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parahGangguanLainnyaRadioButtonActionPerformed

    private void tidakGangguanLainnyaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakGangguanLainnyaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakGangguanLainnyaRadioButtonActionPerformed

    private void buttonNextPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextPanelMouseClicked
        // TODO add your handling code here:

        gangguan.setPenglihatan(getSelected(penglihatanButtonGroup));
        gangguan.setPenglihatan(getSelected(pendengaranButtonGroup));
        gangguan.setKomunikasi(getSelected(caraKomunikasiButtonGroup));
        gangguan.setMobilitas(getSelected(mobilitasButtonGroup));
        gangguan.setGerakkanJariAtauTngn(getSelected(gerakanJariButtonGroup));
        gangguan.setLainnya(getSelected(linnyaButtonGroup));
        kU.setGangguan(gangguan);
        kU.setIjazahTerakhir(ijazahComboBox.getSelectedItem().toString());

        kU.setJurusan(bidangStudiTextField.getText());
        kU.setKewarganegaraan(kewarganegaraanTextField1.getText());
        kU.setPernahPelatihan(getSelected(pelatihanKerjaButtonGroup));
        kU.setNegaraAtauProv(provinsiTextField.getText());
        kU.setKabKota(kabKotaTextField.getText());
        art.setKarakteristikUmum(kU);

        mainScrollPane.setViewportView(new KegiatanSemingguYangLalu_Panel());
    }//GEN-LAST:event_buttonNextPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bidangStudiTextField;
    private javax.swing.JPanel buttonNextPanel;
    private javax.swing.ButtonGroup caraKomunikasiButtonGroup;
    private javax.swing.ButtonGroup gerakanJariButtonGroup;
    private javax.swing.JComboBox<String> ijazahComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel judulAPanel;
    private javax.swing.JTextField kabKotaTextField;
    private javax.swing.JTextField kewarganegaraanTextField1;
    private javax.swing.ButtonGroup linnyaButtonGroup;
    private javax.swing.ButtonGroup mobilitasButtonGroup;
    private javax.swing.JRadioButton negatifPelatihanKerjaRadioButton;
    private javax.swing.JRadioButton parahGangguanJarRadioButton;
    private javax.swing.JRadioButton parahGangguanKomRadioButton;
    private javax.swing.JRadioButton parahGangguanLainnyaRadioButton;
    private javax.swing.JRadioButton parahGangguanMobRadioButton;
    private javax.swing.JRadioButton parahGangguanPenglihatanRadioButton;
    private javax.swing.JRadioButton parahGangguanPennglihatanRadioButton;
    private javax.swing.ButtonGroup pelatihanKerjaButtonGroup;
    private javax.swing.JRadioButton pelatihanKerjaPositifRadioButton;
    private javax.swing.ButtonGroup pendengaranButtonGroup;
    private javax.swing.ButtonGroup penglihatanButtonGroup;
    private javax.swing.JTextField provinsiTextField;
    private javax.swing.JRadioButton sedangGangguanJariRadioButton;
    private javax.swing.JRadioButton sedangGangguanKomRadioButton;
    private javax.swing.JRadioButton sedangGangguanMobRadioButton;
    private javax.swing.JRadioButton sedangGangguanPendengaranRadioButton;
    private javax.swing.JRadioButton sedangGangguanPenglihatanRadioButton;
    private javax.swing.JRadioButton sedangGangguanRadioButton;
    private javax.swing.JRadioButton tidakGangguanJariRadioButton;
    private javax.swing.JRadioButton tidakGangguanKomRadioButton;
    private javax.swing.JRadioButton tidakGangguanLainnyaRadioButton;
    private javax.swing.JRadioButton tidakGangguanMobRadioButton;
    private javax.swing.JRadioButton tidakGangguanPendengaranRadioButton;
    private javax.swing.JRadioButton tidakGangguanPenglihatanRadioButton;
    // End of variables declaration//GEN-END:variables
}
