/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_7_oop.Panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.JScrollPane;
import kelompok_7_oop.Kelas.AnggotaRuta;
import kelompok_7_oop.Kelas.KegiatanMingguLalu;
import kelompok_7_oop.Kelas.WaktuBekerja;

/**
 *
 * @author USER-PC
 */
public class KegiatanSemingguYangLalu_Panel extends javax.swing.JPanel {

    private JScrollPane mainScrollPane;
    private AnggotaRuta art;
    private KegiatanMingguLalu mingguLalu = new KegiatanMingguLalu();

    /**
     * Creates new form KegiatanSemingguYangLalu_Panel
     */
    public String getSelected(ButtonGroup bg) {
        for (Enumeration<AbstractButton> buttons = bg.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "";
    }
    private boolean flag = true;

    public KegiatanSemingguYangLalu_Panel(JScrollPane mainJScrollPane, AnggotaRuta ruta) {
        initComponents();
        this.mainScrollPane = mainJScrollPane;
        this.art = ruta;
        kegWktTerbanyak_1RadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainScrollPane.setViewportView(new MencariKerjaPanel(mainScrollPane, art));
            }
        });
        negatifSementaraNganggurRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainScrollPane.setViewportView(new MencariKerjaPanel(mainScrollPane, art));
            }
        });
        positifTidakBekerjaRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainScrollPane.setViewportView(new MencariKerjaPanel(mainScrollPane, art));
            }
        });
        negatifKegiatanLainRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String kerja = getSelected(bekerja_buttonGroup);
                String sekolah = getSelected(sekolah_buttonGroup);
                String mengurusRumah = getSelected(mengurusRT_buttonGroup);

                if (kerja.equalsIgnoreCase("tidak") && sekolah.equalsIgnoreCase("tidak") && mengurusRumah.equalsIgnoreCase("tidak")) {
                    Enumeration<AbstractButton> enumeration = kegWktTerbanyak.getElements();
                    while (enumeration.hasMoreElements()) {
                        enumeration.nextElement().setEnabled(false);
                    }
                    flag = false;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bekerja_buttonGroup = new javax.swing.ButtonGroup();
        sekolah_buttonGroup = new javax.swing.ButtonGroup();
        mengurusRT_buttonGroup = new javax.swing.ButtonGroup();
        kegiatanLain_buttonGroup = new javax.swing.ButtonGroup();
        kegWktTerbanyak = new javax.swing.ButtonGroup();
        lapUsahabuttonGroup = new javax.swing.ButtonGroup();
        memperolehGajibuttonGroup = new javax.swing.ButtonGroup();
        tidakBekerjabuttonGroup = new javax.swing.ButtonGroup();
        jaminanKembaliBekerjabuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        positifBekerjaRadioButton = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        negatifBekerjaRadioButton = new javax.swing.JRadioButton();
        positifSekolahRadioButton = new javax.swing.JRadioButton();
        negatifSekolahRadioButton = new javax.swing.JRadioButton();
        negatifMengurusRTRadioButton = new javax.swing.JRadioButton();
        positifMengurusRTRadioButton = new javax.swing.JRadioButton();
        negatifKegiatanLainRadioButton = new javax.swing.JRadioButton();
        positifKegiatanLainRadioButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        kegWktTerbanyak_1RadioButton = new javax.swing.JRadioButton();
        kegWktTerbanyak_2RadioButton = new javax.swing.JRadioButton();
        kegWktTerbanyak_3RadioButton = new javax.swing.JRadioButton();
        kegWktTerbanyak_4RadioButton = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        positifSementaraNganggurRadioButton = new javax.swing.JRadioButton();
        negatifSementaraNganggurRadioButton = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        alasanMenganggurComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        positifMemperolehGajiRadioButton = new javax.swing.JRadioButton();
        negatifMemperolehGajiRadioButton = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        positifTidakBekerjaRadioButton = new javax.swing.JRadioButton();
        negatifTidakBekerjaRadioButton = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        positifJaminanKmblKerjaRadioButton = new javax.swing.JRadioButton();
        negatifJaminanKmblKerjaRadioButton = new javax.swing.JRadioButton();
        buttonNextPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("V.B. KEGIATAN SEMINGGU YANG LALU");

        jLabel2.setText("5.a. Selama seminggu yang lalu : ");

        jLabel5.setText("1. Apakah (NAMA) bekerja?");

        jLabel6.setText("2. Apakah (NAMA) sekolah? ");

        jLabel7.setText("3. Apakah (NAMA) mengurus rumah tangga?");

        jLabel8.setText("4. Apakah (NAMA) melakukan kegiatan lainnya,   "); // NOI18N

        jLabel9.setText(" selain 'kegiatan pribadi'?");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("JIKA R.5.a.1 s.d. R.5.a.4 YANG DILINGKARI ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("KODE \"2\" ATAU $4, LANJUTKAN KE R.6");

        jLabel12.setText("  b. Dari kegiatan 1 s.d. 4 yang menyatakan \"Ya\" diatas, kegiatan apakah ");

        bekerja_buttonGroup.add(positifBekerjaRadioButton);
        positifBekerjaRadioButton.setText("Ya");
        positifBekerjaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positifBekerjaRadioButtonActionPerformed(evt);
            }
        });

        bekerja_buttonGroup.add(negatifBekerjaRadioButton);
        negatifBekerjaRadioButton.setText("Tidak");
        negatifBekerjaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifBekerjaRadioButtonActionPerformed(evt);
            }
        });

        sekolah_buttonGroup.add(positifSekolahRadioButton);
        positifSekolahRadioButton.setText("Ya");
        positifSekolahRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positifSekolahRadioButtonActionPerformed(evt);
            }
        });

        sekolah_buttonGroup.add(negatifSekolahRadioButton);
        negatifSekolahRadioButton.setText("Tidak");
        negatifSekolahRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifSekolahRadioButtonActionPerformed(evt);
            }
        });

        mengurusRT_buttonGroup.add(negatifMengurusRTRadioButton);
        negatifMengurusRTRadioButton.setText("Tidak");
        negatifMengurusRTRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifMengurusRTRadioButtonActionPerformed(evt);
            }
        });

        mengurusRT_buttonGroup.add(positifMengurusRTRadioButton);
        positifMengurusRTRadioButton.setText("Ya");
        positifMengurusRTRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positifMengurusRTRadioButtonActionPerformed(evt);
            }
        });

        kegiatanLain_buttonGroup.add(negatifKegiatanLainRadioButton);
        negatifKegiatanLainRadioButton.setText("Tidak");
        negatifKegiatanLainRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifKegiatanLainRadioButtonActionPerformed(evt);
            }
        });

        kegiatanLain_buttonGroup.add(positifKegiatanLainRadioButton);
        positifKegiatanLainRadioButton.setText("Ya");
        positifKegiatanLainRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positifKegiatanLainRadioButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("      yang menggunakan waktu terbanyak selama seminggu yang lalu?");

        kegWktTerbanyak.add(kegWktTerbanyak_1RadioButton);
        kegWktTerbanyak_1RadioButton.setText("1");
        kegWktTerbanyak_1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kegWktTerbanyak_1RadioButtonActionPerformed(evt);
            }
        });

        kegWktTerbanyak.add(kegWktTerbanyak_2RadioButton);
        kegWktTerbanyak_2RadioButton.setText("2");

        kegWktTerbanyak.add(kegWktTerbanyak_3RadioButton);
        kegWktTerbanyak_3RadioButton.setText("3");

        kegWktTerbanyak.add(kegWktTerbanyak_4RadioButton);
        kegWktTerbanyak_4RadioButton.setText("4");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("-> R.11");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("JIKA 5.a.1 = 1, LANJUTKAN KE R.11");

        jLabel17.setText("<html>6.a. Apakah (NAMA) mempunyai pekerjaan/usaha, tetapi sementara tidak<br>tidak bekerja sela seminggu yang lalu? </html>");

        lapUsahabuttonGroup.add(positifSementaraNganggurRadioButton);
        positifSementaraNganggurRadioButton.setText("YA");

        lapUsahabuttonGroup.add(negatifSementaraNganggurRadioButton);
        negatifSementaraNganggurRadioButton.setText("TIDAK");
        negatifSementaraNganggurRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifSementaraNganggurRadioButtonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("-> R.11");

        jLabel20.setText("7. Apakah alasan utama (NAMA) sementara tidak bekerja selama seminggu");

        jLabel21.setText("yang lalu?");

        alasanMenganggurComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuti (tahunan/sakit/bersalin)", "Sekolah/pendidikan/pelatihan", "Aturan waktu kerja", "Pemogokan kerja", "Penurunan aktivis ekonomi (permintaan pasar / jumlah pesanan)", "Penangguhan kerja (cuaca buruk, kekurangan bahan baku, pergantian musim, dan lain)", "Lainnya, tuliskan ..." }));
        alasanMenganggurComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasanMenganggurComboBoxActionPerformed(evt);
            }
        });

        jLabel22.setText("8. Apakah (NAMA) tetap memperoleh penghasilan/gaji/upah selama periode");

        jLabel23.setText("sementara tidak bekerja?");

        memperolehGajibuttonGroup.add(positifMemperolehGajiRadioButton);
        positifMemperolehGajiRadioButton.setText("YA");

        memperolehGajibuttonGroup.add(negatifMemperolehGajiRadioButton);
        negatifMemperolehGajiRadioButton.setText("TIDAK");
        negatifMemperolehGajiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifMemperolehGajiRadioButtonActionPerformed(evt);
            }
        });

        jLabel24.setText("9. Sudah berapa lama (NAMA) sementara tidak bekerja?");

        tidakBekerjabuttonGroup.add(positifTidakBekerjaRadioButton);
        positifTidakBekerjaRadioButton.setText("0-3 BULAN");
        positifTidakBekerjaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positifTidakBekerjaRadioButtonActionPerformed(evt);
            }
        });

        tidakBekerjabuttonGroup.add(negatifTidakBekerjaRadioButton);
        negatifTidakBekerjaRadioButton.setText("LEBIH DARI 3 BULAN");
        negatifTidakBekerjaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifTidakBekerjaRadioButtonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("-> R.11");

        jLabel27.setText("10. Apakah ada jaminan (NAMA) untuk kembali bekerja pada unit usaha ");

        jLabel28.setText("usaha/tempat kerja sekarang?");

        jaminanKembaliBekerjabuttonGroup.add(positifJaminanKmblKerjaRadioButton);
        positifJaminanKmblKerjaRadioButton.setText("YA");

        jaminanKembaliBekerjabuttonGroup.add(negatifJaminanKmblKerjaRadioButton);
        negatifJaminanKmblKerjaRadioButton.setText("TIDAK");
        negatifJaminanKmblKerjaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatifJaminanKmblKerjaRadioButtonActionPerformed(evt);
            }
        });

        buttonNextPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextPanelMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Next page_48px.png"))); // NOI18N

        javax.swing.GroupLayout buttonNextPanelLayout = new javax.swing.GroupLayout(buttonNextPanel);
        buttonNextPanel.setLayout(buttonNextPanelLayout);
        buttonNextPanelLayout.setHorizontalGroup(
            buttonNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonNextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonNextPanelLayout.setVerticalGroup(
            buttonNextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonNextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(positifTidakBekerjaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(35, 35, 35)
                .addComponent(negatifTidakBekerjaRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(positifJaminanKmblKerjaRadioButton)
                                .addGap(120, 120, 120)
                                .addComponent(negatifJaminanKmblKerjaRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel28))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(positifSementaraNganggurRadioButton)
                                .addGap(120, 120, 120)
                                .addComponent(negatifSementaraNganggurRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alasanMenganggurComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(positifMemperolehGajiRadioButton)
                                .addGap(120, 120, 120)
                                .addComponent(negatifMemperolehGajiRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel23))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(kegWktTerbanyak_1RadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(kegWktTerbanyak_2RadioButton)
                                                    .addGap(40, 40, 40)
                                                    .addComponent(kegWktTerbanyak_3RadioButton)
                                                    .addGap(41, 41, 41)
                                                    .addComponent(kegWktTerbanyak_4RadioButton))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel13)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(positifBekerjaRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(negatifBekerjaRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(positifSekolahRadioButton)
                                            .addComponent(positifMengurusRTRadioButton)
                                            .addComponent(positifKegiatanLainRadioButton))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(negatifSekolahRadioButton)
                                            .addComponent(negatifMengurusRTRadioButton)
                                            .addComponent(negatifKegiatanLainRadioButton))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(buttonNextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel10))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kegWktTerbanyak_1RadioButton)
                            .addComponent(kegWktTerbanyak_2RadioButton)
                            .addComponent(kegWktTerbanyak_3RadioButton)
                            .addComponent(kegWktTerbanyak_4RadioButton)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positifSementaraNganggurRadioButton)
                            .addComponent(negatifSementaraNganggurRadioButton)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alasanMenganggurComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positifMemperolehGajiRadioButton)
                            .addComponent(negatifMemperolehGajiRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positifTidakBekerjaRadioButton)
                            .addComponent(negatifTidakBekerjaRadioButton)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positifJaminanKmblKerjaRadioButton)
                            .addComponent(negatifJaminanKmblKerjaRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positifBekerjaRadioButton)
                            .addComponent(negatifBekerjaRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(positifSekolahRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(positifMengurusRTRadioButton)
                                    .addComponent(negatifMengurusRTRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(positifKegiatanLainRadioButton)
                                    .addComponent(negatifKegiatanLainRadioButton)))
                            .addComponent(negatifSekolahRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void positifBekerjaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positifBekerjaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positifBekerjaRadioButtonActionPerformed

    private void negatifBekerjaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifBekerjaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifBekerjaRadioButtonActionPerformed

    private void positifSekolahRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positifSekolahRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positifSekolahRadioButtonActionPerformed

    private void negatifSekolahRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifSekolahRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifSekolahRadioButtonActionPerformed

    private void negatifMengurusRTRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifMengurusRTRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifMengurusRTRadioButtonActionPerformed

    private void positifMengurusRTRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positifMengurusRTRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positifMengurusRTRadioButtonActionPerformed

    private void negatifKegiatanLainRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifKegiatanLainRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifKegiatanLainRadioButtonActionPerformed

    private void positifKegiatanLainRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positifKegiatanLainRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positifKegiatanLainRadioButtonActionPerformed

    private void kegWktTerbanyak_1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kegWktTerbanyak_1RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kegWktTerbanyak_1RadioButtonActionPerformed

    private void negatifSementaraNganggurRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifSementaraNganggurRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifSementaraNganggurRadioButtonActionPerformed

    private void alasanMenganggurComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasanMenganggurComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alasanMenganggurComboBoxActionPerformed

    private void negatifMemperolehGajiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifMemperolehGajiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifMemperolehGajiRadioButtonActionPerformed

    private void negatifTidakBekerjaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifTidakBekerjaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifTidakBekerjaRadioButtonActionPerformed

    private void positifTidakBekerjaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positifTidakBekerjaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positifTidakBekerjaRadioButtonActionPerformed

    private void negatifJaminanKmblKerjaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatifJaminanKmblKerjaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negatifJaminanKmblKerjaRadioButtonActionPerformed

    private void buttonNextPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextPanelMouseClicked
        // TODO add your handling code here:
        ArrayList<String> temp = new ArrayList<>();
        temp.add(getSelected(bekerja_buttonGroup));
        temp.add(getSelected(sekolah_buttonGroup));
        temp.add(getSelected(mengurusRT_buttonGroup));
        temp.add(getSelected(kegiatanLain_buttonGroup));
        mingguLalu.setKegiatan(temp);
        if (flag == true) {
            mingguLalu.setWaktuTerbanyak(getSelected(kegWktTerbanyak));
        }
        mingguLalu.setSementaraMenganggur(getSelected(lapUsahabuttonGroup));
        mingguLalu.setAlasanMenganggur(alasanMenganggurComboBox.getSelectedItem().toString());
        mingguLalu.setLamaMenganggur(getSelected(tidakBekerjabuttonGroup));
        mingguLalu.setDapatPenghasilan(getSelected(memperolehGajibuttonGroup));
        mingguLalu.setJaminanKembaliKerja(getSelected(jaminanKembaliBekerjabuttonGroup));

        art.setKegiatanMingguLalu(mingguLalu);
    }//GEN-LAST:event_buttonNextPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alasanMenganggurComboBox;
    private javax.swing.ButtonGroup bekerja_buttonGroup;
    private javax.swing.JPanel buttonNextPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup jaminanKembaliBekerjabuttonGroup;
    private javax.swing.ButtonGroup kegWktTerbanyak;
    private javax.swing.JRadioButton kegWktTerbanyak_1RadioButton;
    private javax.swing.JRadioButton kegWktTerbanyak_2RadioButton;
    private javax.swing.JRadioButton kegWktTerbanyak_3RadioButton;
    private javax.swing.JRadioButton kegWktTerbanyak_4RadioButton;
    private javax.swing.ButtonGroup kegiatanLain_buttonGroup;
    private javax.swing.ButtonGroup lapUsahabuttonGroup;
    private javax.swing.ButtonGroup memperolehGajibuttonGroup;
    private javax.swing.ButtonGroup mengurusRT_buttonGroup;
    private javax.swing.JRadioButton negatifBekerjaRadioButton;
    private javax.swing.JRadioButton negatifJaminanKmblKerjaRadioButton;
    private javax.swing.JRadioButton negatifKegiatanLainRadioButton;
    private javax.swing.JRadioButton negatifMemperolehGajiRadioButton;
    private javax.swing.JRadioButton negatifMengurusRTRadioButton;
    private javax.swing.JRadioButton negatifSekolahRadioButton;
    private javax.swing.JRadioButton negatifSementaraNganggurRadioButton;
    private javax.swing.JRadioButton negatifTidakBekerjaRadioButton;
    private javax.swing.JRadioButton positifBekerjaRadioButton;
    private javax.swing.JRadioButton positifJaminanKmblKerjaRadioButton;
    private javax.swing.JRadioButton positifKegiatanLainRadioButton;
    private javax.swing.JRadioButton positifMemperolehGajiRadioButton;
    private javax.swing.JRadioButton positifMengurusRTRadioButton;
    private javax.swing.JRadioButton positifSekolahRadioButton;
    private javax.swing.JRadioButton positifSementaraNganggurRadioButton;
    private javax.swing.JRadioButton positifTidakBekerjaRadioButton;
    private javax.swing.ButtonGroup sekolah_buttonGroup;
    private javax.swing.ButtonGroup tidakBekerjabuttonGroup;
    // End of variables declaration//GEN-END:variables
}
