/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_7_oop.Panel;

import java.util.ArrayList;
import java.util.Enumeration;
import static javafx.scene.input.KeyCode.J;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import kelompok_7_oop.Kelas.AnggotaRuta;
import kelompok_7_oop.Kelas.KegiatanMencariKerja;


/**
 *
 * @author Nashir
 */
public class MencariKerjaPanel extends javax.swing.JPanel {
    private JScrollPane mainScrollPane;
    private AnggotaRuta art;
    KegiatanMencariKerja kmk = new KegiatanMencariKerja();
   
    /**
     * Creates new form MencariKerjaPanel
     */
    private String getSelected(ButtonGroup bg) {
        for (Enumeration<AbstractButton> buttons = bg.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "tidak valid";
    }
    public MencariKerjaPanel(JScrollPane mainScrollPane, AnggotaRuta ruta) {
     
        
        
        initComponents();
        this.mainScrollPane=mainScrollPane;
        this.art=ruta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mencariKerjaGroup = new javax.swing.ButtonGroup();
        mempersiapkanUsahaGroup = new javax.swing.ButtonGroup();
        bukaUsahaButtonGroup = new javax.swing.ButtonGroup();
        tawarankerjaButtonGroup = new javax.swing.ButtonGroup();
        mulaiKerjaButtonGroup = new javax.swing.ButtonGroup();
        inginKerjaButtonGroup = new javax.swing.ButtonGroup();
        judulCPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mencariKerjaPositifRadioButton = new javax.swing.JRadioButton();
        mencariKerjaNegatifRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        persiapanUsahaNegatifRadioButton1 = new javax.swing.JRadioButton();
        persiapanUsahaPositifRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lainnyaUpayaKerjaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alasanTdkMencariKerjaComboBox = new javax.swing.JComboBox<>();
        melamarKerjaCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        menghubungiPerusahaanCheckBox = new javax.swing.JCheckBox();
        lamarIklanKerjaCheckBox = new javax.swing.JCheckBox();
        hubungiKeluargaCheckBox = new javax.swing.JCheckBox();
        iklanDiriCheckBox = new javax.swing.JCheckBox();
        kumpulModalCheckBox = new javax.swing.JCheckBox();
        mencariTptUshCheckBox = new javax.swing.JCheckBox();
        perizinanUsahaCheckBox = new javax.swing.JCheckBox();
        lainnyaKerjaCheckBox = new javax.swing.JCheckBox();
        lainnyaAlasanMencariKerjaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        alasanMencariKerjaComboBox = new javax.swing.JComboBox<>();
        lainnyaAlasanTdkMencariKerjaTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        memulaiUsahaNegatifRadioButton = new javax.swing.JRadioButton();
        memulaiUsahaPositifRadioButton1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        terimaKerjaPositifRadioButton2 = new javax.swing.JRadioButton();
        terimaKerjaNegatifRadioButton1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        mulaiKerjaNegatifRadioButton2 = new javax.swing.JRadioButton();
        mulaiKerjaPositifRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        mauKerjaNegatifRadioButton3 = new javax.swing.JRadioButton();
        mauKerjaPositifRadioButton4 = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        lamaMencariKerjaSpinner = new javax.swing.JSpinner();

        judulCPanel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judulCPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulCPanel.setText("V.C. MENCARI KERJA");

        jLabel1.setText("Selama seminggu lalu anda mencair kerja:");

        mencariKerjaGroup.add(mencariKerjaPositifRadioButton);
        mencariKerjaPositifRadioButton.setText("Ya");

        mencariKerjaGroup.add(mencariKerjaNegatifRadioButton);
        mencariKerjaNegatifRadioButton.setText("Tidak");
        mencariKerjaNegatifRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencariKerjaNegatifRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Apakah (nama) mempersiapkan usaha selama seminggu lalu:");

        mempersiapkanUsahaGroup.add(persiapanUsahaNegatifRadioButton1);
        persiapanUsahaNegatifRadioButton1.setText("Tidak");
        persiapanUsahaNegatifRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persiapanUsahaNegatifRadioButton1ActionPerformed(evt);
            }
        });

        mempersiapkanUsahaGroup.add(persiapanUsahaPositifRadioButton);
        persiapanUsahaPositifRadioButton.setText("Ya");

        jLabel3.setText("Lama mencari kerja atau mempersiapkan usaha:");

        lainnyaUpayaKerjaTextField.setEditable(false);

        jLabel4.setText("Alasan mencari kerja atau mempersiapkan usaha:");

        alasanTdkMencariKerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah diterima bekerja tapi belum mulai bekerja", "Sudah mempunyai usaha tapi belum memulainya", "Putus asa: merasa tidak mungkin mendapatkan pekerjaan", "Merasa sudah cukup/memiliki sumber pendapatan", "Mengurus rumah tangga", "Sedang bersekolah", "Hamil", "Kurangnya infrastruktur", "Mengalami pengucilan/penolakan sosial", "Tidak mampu melakukan pekerjaan", "Lainnya" }));
        alasanTdkMencariKerjaComboBox.setSelectedIndex(-1);

        melamarKerjaCheckBox.setText("Mendaftar pada bursa kesempatan kerja");
        melamarKerjaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                melamarKerjaCheckBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Upaya dalam mencari kerja seminggu lalu:");

        menghubungiPerusahaanCheckBox.setText("Menghubungi perusahaan/kantor");
        menghubungiPerusahaanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menghubungiPerusahaanCheckBoxActionPerformed(evt);
            }
        });

        lamarIklanKerjaCheckBox.setText("Melamar pekerjaan berdasarkan iklan ");
        lamarIklanKerjaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamarIklanKerjaCheckBoxActionPerformed(evt);
            }
        });

        hubungiKeluargaCheckBox.setText("Menghubungi keluarga/kenalan");
        hubungiKeluargaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hubungiKeluargaCheckBoxActionPerformed(evt);
            }
        });

        iklanDiriCheckBox.setText("Mengiklankan diri");
        iklanDiriCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iklanDiriCheckBoxActionPerformed(evt);
            }
        });

        kumpulModalCheckBox.setText("Mengumpulkan modal/perlengkapan");
        kumpulModalCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kumpulModalCheckBoxActionPerformed(evt);
            }
        });

        mencariTptUshCheckBox.setText("Mencari lokasi/tempat usaha");
        mencariTptUshCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencariTptUshCheckBoxActionPerformed(evt);
            }
        });

        perizinanUsahaCheckBox.setText("Mengurus surat perizinan usah");
        perizinanUsahaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perizinanUsahaCheckBoxActionPerformed(evt);
            }
        });

        lainnyaKerjaCheckBox.setText("Lainnya");
        lainnyaKerjaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lainnyaKerjaCheckBoxActionPerformed(evt);
            }
        });

        lainnyaAlasanMencariKerjaTextField.setEditable(false);

        jLabel6.setText("<html>Alasan utama tidak mencari kerja atau mempersiapkan<br>usaha seminggu yang lalu:</html>");

        alasanMencariKerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamat sekolah/tidak bersekolah lagi", "Tanggung jawab mencari nafkah", "Menambah penghasilan", "Pekerjaan yang ada kurang sesuai", "PHK", "Usaha terhenti", "Lainnya" }));
        alasanMencariKerjaComboBox.setSelectedIndex(-1);

        lainnyaAlasanTdkMencariKerjaTextField.setEditable(false);

        jLabel7.setText("Akan memulai usaha dalam tiga bulan kedepan:");

        bukaUsahaButtonGroup.add(memulaiUsahaNegatifRadioButton);
        memulaiUsahaNegatifRadioButton.setText("Tidak");
        memulaiUsahaNegatifRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memulaiUsahaNegatifRadioButtonActionPerformed(evt);
            }
        });

        bukaUsahaButtonGroup.add(memulaiUsahaPositifRadioButton1);
        memulaiUsahaPositifRadioButton1.setText("Ya");

        jLabel8.setText("Akan menerima penawaran kerja:");

        tawarankerjaButtonGroup.add(terimaKerjaPositifRadioButton2);
        terimaKerjaPositifRadioButton2.setText("Ya");

        tawarankerjaButtonGroup.add(terimaKerjaNegatifRadioButton1);
        terimaKerjaNegatifRadioButton1.setText("Tidak");
        terimaKerjaNegatifRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terimaKerjaNegatifRadioButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Bersedia memulai pekerjaan tersebut dalam dua minggu kedepan:");

        mulaiKerjaButtonGroup.add(mulaiKerjaNegatifRadioButton2);
        mulaiKerjaNegatifRadioButton2.setText("Tidak");
        mulaiKerjaNegatifRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiKerjaNegatifRadioButton2ActionPerformed(evt);
            }
        });

        mulaiKerjaButtonGroup.add(mulaiKerjaPositifRadioButton3);
        mulaiKerjaPositifRadioButton3.setText("Ya");

        jLabel10.setText("Apakah menginginkan pekerjaan:");

        inginKerjaButtonGroup.add(mauKerjaNegatifRadioButton3);
        mauKerjaNegatifRadioButton3.setText("Tidak");
        mauKerjaNegatifRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mauKerjaNegatifRadioButton3ActionPerformed(evt);
            }
        });

        inginKerjaButtonGroup.add(mauKerjaPositifRadioButton4);
        mauKerjaPositifRadioButton4.setText("Ya");

        nextButton.setText("next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lainnyaAlasanTdkMencariKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alasanTdkMencariKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(persiapanUsahaPositifRadioButton)
                                        .addGap(49, 49, 49)
                                        .addComponent(persiapanUsahaNegatifRadioButton1))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lainnyaUpayaKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(melamarKerjaCheckBox)
                                            .addComponent(lainnyaKerjaCheckBox)
                                            .addComponent(perizinanUsahaCheckBox)
                                            .addComponent(mencariTptUshCheckBox)
                                            .addComponent(kumpulModalCheckBox)
                                            .addComponent(hubungiKeluargaCheckBox)
                                            .addComponent(iklanDiriCheckBox)
                                            .addComponent(lamarIklanKerjaCheckBox)
                                            .addComponent(menghubungiPerusahaanCheckBox)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lainnyaAlasanMencariKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alasanMencariKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mauKerjaPositifRadioButton4)
                                                .addGap(49, 49, 49)
                                                .addComponent(mauKerjaNegatifRadioButton3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mulaiKerjaPositifRadioButton3)
                                                .addGap(49, 49, 49)
                                                .addComponent(mulaiKerjaNegatifRadioButton2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(terimaKerjaPositifRadioButton2)
                                                .addGap(49, 49, 49)
                                                .addComponent(terimaKerjaNegatifRadioButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(memulaiUsahaPositifRadioButton1)
                                                .addGap(49, 49, 49)
                                                .addComponent(memulaiUsahaNegatifRadioButton)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(judulCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(mencariKerjaPositifRadioButton)
                                        .addGap(49, 49, 49)
                                        .addComponent(mencariKerjaNegatifRadioButton))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 250, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lamaMencariKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 135, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mencariKerjaPositifRadioButton)
                    .addComponent(mencariKerjaNegatifRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persiapanUsahaPositifRadioButton)
                    .addComponent(persiapanUsahaNegatifRadioButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamaMencariKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alasanMencariKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainnyaAlasanMencariKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(melamarKerjaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menghubungiPerusahaanCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamarIklanKerjaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iklanDiriCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hubungiKeluargaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kumpulModalCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mencariTptUshCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perizinanUsahaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainnyaKerjaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainnyaUpayaKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alasanTdkMencariKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainnyaAlasanTdkMencariKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memulaiUsahaPositifRadioButton1)
                    .addComponent(memulaiUsahaNegatifRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terimaKerjaPositifRadioButton2)
                    .addComponent(terimaKerjaNegatifRadioButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mulaiKerjaPositifRadioButton3)
                    .addComponent(mulaiKerjaNegatifRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mauKerjaPositifRadioButton4)
                    .addComponent(mauKerjaNegatifRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mencariKerjaNegatifRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencariKerjaNegatifRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mencariKerjaNegatifRadioButtonActionPerformed

    private void persiapanUsahaNegatifRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persiapanUsahaNegatifRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persiapanUsahaNegatifRadioButton1ActionPerformed

    private void melamarKerjaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_melamarKerjaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_melamarKerjaCheckBoxActionPerformed

    private void menghubungiPerusahaanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menghubungiPerusahaanCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menghubungiPerusahaanCheckBoxActionPerformed

    private void lamarIklanKerjaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamarIklanKerjaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamarIklanKerjaCheckBoxActionPerformed

    private void hubungiKeluargaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hubungiKeluargaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hubungiKeluargaCheckBoxActionPerformed

    private void iklanDiriCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iklanDiriCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iklanDiriCheckBoxActionPerformed

    private void kumpulModalCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kumpulModalCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kumpulModalCheckBoxActionPerformed

    private void mencariTptUshCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencariTptUshCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mencariTptUshCheckBoxActionPerformed

    private void perizinanUsahaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perizinanUsahaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perizinanUsahaCheckBoxActionPerformed

    private void lainnyaKerjaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lainnyaKerjaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lainnyaKerjaCheckBoxActionPerformed

    private void memulaiUsahaNegatifRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memulaiUsahaNegatifRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memulaiUsahaNegatifRadioButtonActionPerformed

    private void terimaKerjaNegatifRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terimaKerjaNegatifRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terimaKerjaNegatifRadioButton1ActionPerformed

    private void mulaiKerjaNegatifRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiKerjaNegatifRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaiKerjaNegatifRadioButton2ActionPerformed

    private void mauKerjaNegatifRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mauKerjaNegatifRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mauKerjaNegatifRadioButton3ActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        kmk.setMencariKerja(getSelected(mencariKerjaGroup));
        kmk.setMempersiapkanUsaha(getSelected(mempersiapkanUsahaGroup));
        kmk.setLamaMencariKerja(Integer.parseInt(lamaMencariKerjaSpinner.getValue().toString()));
        kmk.setAlasanMencariKerja(alasanMencariKerjaComboBox.getSelectedItem().toString());
        if(alasanMencariKerjaComboBox.getSelectedItem()=="Lainnya"){
            kmk.setAlasanMencariKerja(lainnyaAlasanMencariKerjaTextField.getText());
        }
        if(melamarKerjaCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(melamarKerjaCheckBox.getText());
        }
        if(menghubungiPerusahaanCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(menghubungiPerusahaanCheckBox.getText());
        }
        if(lamarIklanKerjaCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(lamarIklanKerjaCheckBox.getText());
        }
        if(iklanDiriCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(iklanDiriCheckBox.getText());
        }
        if(hubungiKeluargaCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(hubungiKeluargaCheckBox.getText());
        }
        if(kumpulModalCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(kumpulModalCheckBox.getText());
        }
        if(mencariTptUshCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(mencariTptUshCheckBox.getText());
        }
        if(perizinanUsahaCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(melamarKerjaCheckBox.getText());
        }
        if(lainnyaKerjaCheckBox.isSelected()){
            kmk.addUpayaMencariKerja(lainnyaUpayaKerjaTextField.getText());
        }
        
        kmk.setAlasanTdkMencariKerja(alasanTdkMencariKerjaComboBox.getSelectedItem().toString());
        if (alasanTdkMencariKerjaComboBox.getSelectedItem().toString().equalsIgnoreCase("Lainnya")){  
            kmk.setAlasanTdkMencariKerja(lainnyaAlasanTdkMencariKerjaTextField.getText());
        }
        kmk.setMulaiPekerjaan(getSelected(mulaiKerjaButtonGroup));
        kmk.setMenerimaTawaran(getSelected(tawarankerjaButtonGroup));
        kmk.setSiapKerja(getSelected(mulaiKerjaButtonGroup));
        kmk.setInginPekerjaan(getSelected(inginKerjaButtonGroup));
//        JOptionPane.showMessageDialog(this, "Success");
        mainScrollPane.setViewportView(new PekerjaanUtamaPanel(mainScrollPane, art));

    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alasanMencariKerjaComboBox;
    private javax.swing.JComboBox<String> alasanTdkMencariKerjaComboBox;
    private javax.swing.ButtonGroup bukaUsahaButtonGroup;
    private javax.swing.JCheckBox hubungiKeluargaCheckBox;
    private javax.swing.JCheckBox iklanDiriCheckBox;
    private javax.swing.ButtonGroup inginKerjaButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel judulCPanel;
    private javax.swing.JCheckBox kumpulModalCheckBox;
    private javax.swing.JTextField lainnyaAlasanMencariKerjaTextField;
    private javax.swing.JTextField lainnyaAlasanTdkMencariKerjaTextField;
    private javax.swing.JCheckBox lainnyaKerjaCheckBox;
    private javax.swing.JTextField lainnyaUpayaKerjaTextField;
    private javax.swing.JSpinner lamaMencariKerjaSpinner;
    private javax.swing.JCheckBox lamarIklanKerjaCheckBox;
    private javax.swing.JRadioButton mauKerjaNegatifRadioButton3;
    private javax.swing.JRadioButton mauKerjaPositifRadioButton4;
    private javax.swing.JCheckBox melamarKerjaCheckBox;
    private javax.swing.ButtonGroup mempersiapkanUsahaGroup;
    private javax.swing.JRadioButton memulaiUsahaNegatifRadioButton;
    private javax.swing.JRadioButton memulaiUsahaPositifRadioButton1;
    private javax.swing.ButtonGroup mencariKerjaGroup;
    private javax.swing.JRadioButton mencariKerjaNegatifRadioButton;
    private javax.swing.JRadioButton mencariKerjaPositifRadioButton;
    private javax.swing.JCheckBox mencariTptUshCheckBox;
    private javax.swing.JCheckBox menghubungiPerusahaanCheckBox;
    private javax.swing.ButtonGroup mulaiKerjaButtonGroup;
    private javax.swing.JRadioButton mulaiKerjaNegatifRadioButton2;
    private javax.swing.JRadioButton mulaiKerjaPositifRadioButton3;
    private javax.swing.JButton nextButton;
    private javax.swing.JCheckBox perizinanUsahaCheckBox;
    private javax.swing.JRadioButton persiapanUsahaNegatifRadioButton1;
    private javax.swing.JRadioButton persiapanUsahaPositifRadioButton;
    private javax.swing.ButtonGroup tawarankerjaButtonGroup;
    private javax.swing.JRadioButton terimaKerjaNegatifRadioButton1;
    private javax.swing.JRadioButton terimaKerjaPositifRadioButton2;
    // End of variables declaration//GEN-END:variables

}
