/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_7_oop.Panel;

/**
 *
 * @author Nashir
 */
public class PekerjaanUtamaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PekerjaanUtamaPanel
     */
    public PekerjaanUtamaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pakaiSndiriButtonGroup = new javax.swing.ButtonGroup();
        jamKesButtonGroup = new javax.swing.ButtonGroup();
        jamKecKerjaButtonGroup = new javax.swing.ButtonGroup();
        jamTuaButtonGroup = new javax.swing.ButtonGroup();
        jamPensButtonGroup = new javax.swing.ButtonGroup();
        jamMatiButtonGroup = new javax.swing.ButtonGroup();
        cutiButtonGroup = new javax.swing.ButtonGroup();
        pesangonButtonGroup = new javax.swing.ButtonGroup();
        serikatKerjaButtonGroup = new javax.swing.ButtonGroup();
        judulDPanel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lapanganKerjaUtmTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jenisKerjaUtmTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lamaKerjaUtmTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lamaKerjaUtmTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        seninJamKerjaTextField = new javax.swing.JTextField();
        selasaJamKerjaTextField = new javax.swing.JTextField();
        rabuJamKerjaTextField = new javax.swing.JTextField();
        kamisJamKerjaTextField = new javax.swing.JTextField();
        jumatJamKerjaTextField = new javax.swing.JTextField();
        sabtuJamKerjaTextField = new javax.swing.JTextField();
        mingguJamKerjaTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jamKerjaBiasaTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        statusKedudukanKerjaComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        caraPembukuanComboBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        dipakaiSndriNegatifRadioButton1 = new javax.swing.JRadioButton();
        dipakaiSndriPositifRadioButton = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        upahUangTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        upahBarangTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sistemPmbayaranComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        tidakTahuJamKesRadioButton = new javax.swing.JRadioButton();
        yaJamKesRadioButton = new javax.swing.JRadioButton();
        tidakJamKesRadioButton = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        tidakTahuJamKecKerjaRadioButton1 = new javax.swing.JRadioButton();
        tidakJamKecKerjaRadioButton1 = new javax.swing.JRadioButton();
        yaJamKecKerjaRadioButton1 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        tidakTahuJamTuaRadioButton = new javax.swing.JRadioButton();
        tidakJamTuaRadioButton = new javax.swing.JRadioButton();
        yaJamTuaRadioButton = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        tidakTahuJamPensRadioButton = new javax.swing.JRadioButton();
        tidakJamPensRadioButton = new javax.swing.JRadioButton();
        yaJamPensRadioButton = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        tidakTahuJamMatiRadioButton = new javax.swing.JRadioButton();
        tidakJamMatiRadioButton = new javax.swing.JRadioButton();
        yaJamMatiRadioButton = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        tidakTahuCutiRadioButton = new javax.swing.JRadioButton();
        tidakCutiRadioButton = new javax.swing.JRadioButton();
        yaCutiRadioButton = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        tidakTahuPesangonRadioButton = new javax.swing.JRadioButton();
        tidakPesangonRadioButton = new javax.swing.JRadioButton();
        yaPesangonRadioButton = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        sistemPmbayaranComboBox1 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        tidakTahuJamKesRadioButton1 = new javax.swing.JRadioButton();
        tidakJamKesRadioButton1 = new javax.swing.JRadioButton();
        yaJamKesRadioButton1 = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        jenisInstansiComboBox = new javax.swing.JComboBox<>();
        lainyaInstansiTextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tempatKerjaComboBox = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        provNegTextField = new javax.swing.JTextField();
        kabKotaTextField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jarakTempatKerjaComboBox = new javax.swing.JComboBox<>();
        setiapHariRadioButton = new javax.swing.JRadioButton();
        setiapMingguRadioButton = new javax.swing.JRadioButton();
        setiapBulanRadioButton = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        lamaJalanComboBox = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jenisTransportComboBox = new javax.swing.JComboBox<>();

        jLabel1.setText("Selama seminggu lalu anda mencair kerja:");

        judulDPanel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judulDPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulDPanel.setText("V.D. PEKERJAAN UTAMA");

        jLabel2.setText("Nama lapangan pekerjaan utama seminggu lalu:");

        lapanganKerjaUtmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapanganKerjaUtmTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis pekerjaan/jabatan dari pekerjaan utama seminggu lalu:");

        jenisKerjaUtmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKerjaUtmTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Lama bekerja di pekerjaan utama:");

        lamaKerjaUtmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaKerjaUtmTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Lama mencari pekerjaan/mempersiapkan usaha di pkerjaan utama:");

        lamaKerjaUtmTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaKerjaUtmTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Jumlah jam kerja dalam pekerjaan utama:");

        jLabel7.setText("Senin:");

        jLabel8.setText("Selasa:");

        jLabel9.setText("Minggu:");

        jLabel10.setText("Kamis:");

        jLabel11.setText("Jum'at:");

        jLabel12.setText("Sabtu:");

        jLabel13.setText("Rabu:");

        seninJamKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seninJamKerjaTextFieldActionPerformed(evt);
            }
        });

        selasaJamKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selasaJamKerjaTextFieldActionPerformed(evt);
            }
        });

        rabuJamKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabuJamKerjaTextFieldActionPerformed(evt);
            }
        });

        kamisJamKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamisJamKerjaTextFieldActionPerformed(evt);
            }
        });

        jumatJamKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumatJamKerjaTextFieldActionPerformed(evt);
            }
        });

        sabtuJamKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabtuJamKerjaTextFieldActionPerformed(evt);
            }
        });

        mingguJamKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mingguJamKerjaTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Jam kerja biasanya dalam seminggu:");

        jamKerjaBiasaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamKerjaBiasaTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Status kedudukan pada pekerjaan utama selama seminggu lalu:");

        statusKedudukanKerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berusaha sendiri", "Dibantu buruh tidak tetap/pekerja keluarga/tidak dibayar", "Dibantu buruh tetap/dibayar", "Buruh/karyawan/pegawai", "Pekerja bebas di pertanian", "Pekerja bebas di nonpertanian", "Pekerja keluarga/tidak dibayar" }));
        statusKedudukanKerjaComboBox.setSelectedIndex(-1);

        jLabel16.setText("Cara perusahaan melakukan pembukuan:");

        caraPembukuanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak ada pembukuan tertulis", "Ada, pembukuan sederhana", "Pembukuan lengkap (laba/rugi dan neraca)", "Tidak tahu" }));
        caraPembukuanComboBox.setSelectedIndex(-1);

        jLabel17.setText("<html>Barang/jasa yang dihasilkan dari pekerjaan seminggu yang lalu<br>diutamakan untuk digunakan sendiri:</html>");

        pakaiSndiriButtonGroup.add(dipakaiSndriNegatifRadioButton1);
        dipakaiSndriNegatifRadioButton1.setText("Tidak");
        dipakaiSndriNegatifRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dipakaiSndriNegatifRadioButton1ActionPerformed(evt);
            }
        });

        pakaiSndiriButtonGroup.add(dipakaiSndriPositifRadioButton);
        dipakaiSndriPositifRadioButton.setText("Ya");

        jLabel18.setText("Upah bersih yang diterima (uang & barang):");

        jLabel19.setText("Uang:");

        upahUangTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upahUangTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setText("Barang:");

        upahBarangTextField.setToolTipText("Konversi menjadi uang");
        upahBarangTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upahBarangTextFieldActionPerformed(evt);
            }
        });

        jLabel21.setText("Sistem pembayaran/pengupahan pekerjaan utama:");

        sistemPmbayaranComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulanan", "Mingguan", "Harian", "Borongan", "Dibayar persatuan hasil" }));
        sistemPmbayaranComboBox.setSelectedIndex(-1);

        jLabel22.setText("Fasilitas pekerjaan:");

        jamKesButtonGroup.add(tidakTahuJamKesRadioButton);
        tidakTahuJamKesRadioButton.setText("Tidak tahu");
        tidakTahuJamKesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamKesRadioButtonActionPerformed(evt);
            }
        });

        jamKesButtonGroup.add(yaJamKesRadioButton);
        yaJamKesRadioButton.setText("Ya");
        yaJamKesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamKesRadioButtonActionPerformed(evt);
            }
        });

        jamKesButtonGroup.add(tidakJamKesRadioButton);
        tidakJamKesRadioButton.setText("Tidak");
        tidakJamKesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamKesRadioButtonActionPerformed(evt);
            }
        });

        jLabel23.setText("Jaminan kesehatan");

        jamKecKerjaButtonGroup.add(tidakTahuJamKecKerjaRadioButton1);
        tidakTahuJamKecKerjaRadioButton1.setText("Tidak tahu");
        tidakTahuJamKecKerjaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamKecKerjaRadioButton1ActionPerformed(evt);
            }
        });

        jamKecKerjaButtonGroup.add(tidakJamKecKerjaRadioButton1);
        tidakJamKecKerjaRadioButton1.setText("Tidak");
        tidakJamKecKerjaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamKecKerjaRadioButton1ActionPerformed(evt);
            }
        });

        jamKecKerjaButtonGroup.add(yaJamKecKerjaRadioButton1);
        yaJamKecKerjaRadioButton1.setText("Ya");
        yaJamKecKerjaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamKecKerjaRadioButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Jaminan kecelakaan kerja");

        jamTuaButtonGroup.add(tidakTahuJamTuaRadioButton);
        tidakTahuJamTuaRadioButton.setText("Tidak tahu");
        tidakTahuJamTuaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamTuaRadioButtonActionPerformed(evt);
            }
        });

        jamTuaButtonGroup.add(tidakJamTuaRadioButton);
        tidakJamTuaRadioButton.setText("Tidak");
        tidakJamTuaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamTuaRadioButtonActionPerformed(evt);
            }
        });

        jamTuaButtonGroup.add(yaJamTuaRadioButton);
        yaJamTuaRadioButton.setText("Ya");
        yaJamTuaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamTuaRadioButtonActionPerformed(evt);
            }
        });

        jLabel25.setText("Jaminan hari tua");

        jamPensButtonGroup.add(tidakTahuJamPensRadioButton);
        tidakTahuJamPensRadioButton.setText("Tidak tahu");
        tidakTahuJamPensRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamPensRadioButtonActionPerformed(evt);
            }
        });

        jamPensButtonGroup.add(tidakJamPensRadioButton);
        tidakJamPensRadioButton.setText("Tidak");
        tidakJamPensRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamPensRadioButtonActionPerformed(evt);
            }
        });

        jamPensButtonGroup.add(yaJamPensRadioButton);
        yaJamPensRadioButton.setText("Ya");
        yaJamPensRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamPensRadioButtonActionPerformed(evt);
            }
        });

        jLabel26.setText("Jaminan pensiun");

        jamMatiButtonGroup.add(tidakTahuJamMatiRadioButton);
        tidakTahuJamMatiRadioButton.setText("Tidak tahu");
        tidakTahuJamMatiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamMatiRadioButtonActionPerformed(evt);
            }
        });

        jamMatiButtonGroup.add(tidakJamMatiRadioButton);
        tidakJamMatiRadioButton.setText("Tidak");
        tidakJamMatiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamMatiRadioButtonActionPerformed(evt);
            }
        });

        jamMatiButtonGroup.add(yaJamMatiRadioButton);
        yaJamMatiRadioButton.setText("Ya");
        yaJamMatiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamMatiRadioButtonActionPerformed(evt);
            }
        });

        jLabel27.setText("Jaminan kematian");

        cutiButtonGroup.add(tidakTahuCutiRadioButton);
        tidakTahuCutiRadioButton.setText("Tidak tahu");
        tidakTahuCutiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuCutiRadioButtonActionPerformed(evt);
            }
        });

        cutiButtonGroup.add(tidakCutiRadioButton);
        tidakCutiRadioButton.setText("Tidak");
        tidakCutiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakCutiRadioButtonActionPerformed(evt);
            }
        });

        cutiButtonGroup.add(yaCutiRadioButton);
        yaCutiRadioButton.setText("Ya");
        yaCutiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaCutiRadioButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Cuti tanpa potong upah");

        pesangonButtonGroup.add(tidakTahuPesangonRadioButton);
        tidakTahuPesangonRadioButton.setText("Tidak tahu");
        tidakTahuPesangonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuPesangonRadioButtonActionPerformed(evt);
            }
        });

        pesangonButtonGroup.add(tidakPesangonRadioButton);
        tidakPesangonRadioButton.setText("Tidak");
        tidakPesangonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakPesangonRadioButtonActionPerformed(evt);
            }
        });

        pesangonButtonGroup.add(yaPesangonRadioButton);
        yaPesangonRadioButton.setText("Ya");
        yaPesangonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaPesangonRadioButtonActionPerformed(evt);
            }
        });

        jLabel29.setText("Pesangon");

        jLabel30.setText("Jenis perjanjian atau kontrak kerja:");

        sistemPmbayaranComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perjanjian Kerja Waktu Tidak Tertentu", "Perjanjian Kerja Waktu Tertentu", "Perjanjian Lisan", "Tidak ada perjanjian/kontrak kerja", "Tidak tahu" }));
        sistemPmbayaranComboBox1.setSelectedIndex(-1);

        jLabel31.setText("Terlibat dalam serikat pekerja:");

        serikatKerjaButtonGroup.add(tidakTahuJamKesRadioButton1);
        tidakTahuJamKesRadioButton1.setText("Tidak tahu");
        tidakTahuJamKesRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamKesRadioButton1ActionPerformed(evt);
            }
        });

        serikatKerjaButtonGroup.add(tidakJamKesRadioButton1);
        tidakJamKesRadioButton1.setText("Tidak");
        tidakJamKesRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamKesRadioButton1ActionPerformed(evt);
            }
        });

        serikatKerjaButtonGroup.add(yaJamKesRadioButton1);
        yaJamKesRadioButton1.setText("Ya");
        yaJamKesRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamKesRadioButton1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Jenis instansi/lembaga/institusi dari tempat kerja/usaha:");

        jenisInstansiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemerintah/negeri", "Lembaga/organisasi internasional", "Lembaga nonprofit/nirlaba", "Lembaga profit (perusahaan swasta, BUMN, BUMD)", "Koperasi", "Usaha perorangan/usaha rumah tangga", "Rumah tangga", "Lainnya", "Tidak tahu" }));
        jenisInstansiComboBox.setSelectedIndex(-1);

        lainyaInstansiTextField.setEditable(false);

        jLabel33.setText("Lokasi utama tempat kerja:");

        tempatKerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rumah sendiri  ", "Rumah keluarga/teman", "Rumah pemberi kerja", "Lainnya" }));
        tempatKerjaComboBox.setSelectedIndex(-1);

        jLabel34.setText("Letak tempat kerja:");

        kabKotaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabKotaTextFieldActionPerformed(evt);
            }
        });

        jLabel35.setText("Pulang/pergi tempat kerja:");

        jLabel36.setText("Jarak rumah ke tempat kerja:");

        jarakTempatKerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< 10 Km", "10 – 29 Km", "≥ 30 Km", "Tidak tahu" }));
        jarakTempatKerjaComboBox.setSelectedIndex(-1);
        jarakTempatKerjaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarakTempatKerjaComboBoxActionPerformed(evt);
            }
        });

        setiapHariRadioButton.setText("Setiap Hari");

        setiapMingguRadioButton.setText("Setiap Minggu");

        setiapBulanRadioButton.setText("Setiap Bulan");

        jLabel37.setText("Lama perjalanan ke tempat kerja:");

        lamaJalanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤ 30 Menit", "31 – 60 Menit", "61 – 120 Menit", "> 120 Menit" }));
        lamaJalanComboBox.setSelectedIndex(-1);
        lamaJalanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaJalanComboBoxActionPerformed(evt);
            }
        });

        jLabel38.setText("Jenis transportasi ke tempat kerja:");

        jenisTransportComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transportasi umum", "Transportasi bersama", "Transportasi pribadi", "Jalan kaki" }));
        jenisTransportComboBox.setSelectedIndex(-1);
        jenisTransportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisTransportComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lapanganKerjaUtmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenisTransportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lamaJalanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jarakTempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(setiapHariRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(setiapMingguRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(setiapBulanRadioButton))
                                    .addComponent(tempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jenisInstansiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yaJamKesRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tidakJamKesRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tidakTahuJamKesRadioButton1))
                                    .addComponent(sistemPmbayaranComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(upahBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(upahUangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jenisKerjaUtmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lamaKerjaUtmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lamaKerjaUtmTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(seninJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selasaJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rabuJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamisJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel9))
                                            .addComponent(jumatJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sabtuJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mingguJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jamKerjaBiasaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(caraPembukuanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusKedudukanKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dipakaiSndriPositifRadioButton)
                                        .addGap(49, 49, 49)
                                        .addComponent(dipakaiSndriNegatifRadioButton1))
                                    .addComponent(jLabel23)
                                    .addComponent(sistemPmbayaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(196, 196, 196)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaJamKesRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakJamKesRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakTahuJamKesRadioButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaJamKecKerjaRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakJamKecKerjaRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakTahuJamKecKerjaRadioButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaJamTuaRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakJamTuaRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakTahuJamTuaRadioButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaJamPensRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakJamPensRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakTahuJamPensRadioButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaJamMatiRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakJamMatiRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakTahuJamMatiRadioButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaCutiRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakCutiRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakTahuCutiRadioButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaPesangonRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakPesangonRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tidakTahuPesangonRadioButton))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(provNegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lainyaInstansiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lapanganKerjaUtmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisKerjaUtmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamaKerjaUtmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamaKerjaUtmTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(seninJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kamisJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mingguJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(selasaJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumatJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(rabuJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sabtuJamKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jamKerjaBiasaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusKedudukanKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caraPembukuanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dipakaiSndriPositifRadioButton)
                    .addComponent(dipakaiSndriNegatifRadioButton1))
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(upahUangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(upahBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sistemPmbayaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(yaJamKesRadioButton)
                    .addComponent(tidakJamKesRadioButton)
                    .addComponent(tidakTahuJamKesRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(yaJamKecKerjaRadioButton1)
                    .addComponent(tidakJamKecKerjaRadioButton1)
                    .addComponent(tidakTahuJamKecKerjaRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(yaJamTuaRadioButton)
                    .addComponent(tidakJamTuaRadioButton)
                    .addComponent(tidakTahuJamTuaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(yaJamPensRadioButton)
                    .addComponent(tidakJamPensRadioButton)
                    .addComponent(tidakTahuJamPensRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(yaJamMatiRadioButton)
                    .addComponent(tidakJamMatiRadioButton)
                    .addComponent(tidakTahuJamMatiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(yaCutiRadioButton)
                    .addComponent(tidakCutiRadioButton)
                    .addComponent(tidakTahuCutiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(yaPesangonRadioButton)
                    .addComponent(tidakPesangonRadioButton)
                    .addComponent(tidakTahuPesangonRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sistemPmbayaranComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yaJamKesRadioButton1)
                    .addComponent(tidakJamKesRadioButton1)
                    .addComponent(tidakTahuJamKesRadioButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisInstansiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainyaInstansiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provNegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setiapHariRadioButton)
                    .addComponent(setiapMingguRadioButton)
                    .addComponent(setiapBulanRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jarakTempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamaJalanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisTransportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lapanganKerjaUtmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapanganKerjaUtmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lapanganKerjaUtmTextFieldActionPerformed

    private void jenisKerjaUtmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKerjaUtmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisKerjaUtmTextFieldActionPerformed

    private void lamaKerjaUtmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaKerjaUtmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaKerjaUtmTextFieldActionPerformed

    private void lamaKerjaUtmTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaKerjaUtmTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaKerjaUtmTextField1ActionPerformed

    private void seninJamKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seninJamKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seninJamKerjaTextFieldActionPerformed

    private void selasaJamKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selasaJamKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selasaJamKerjaTextFieldActionPerformed

    private void rabuJamKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabuJamKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rabuJamKerjaTextFieldActionPerformed

    private void kamisJamKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamisJamKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kamisJamKerjaTextFieldActionPerformed

    private void jumatJamKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumatJamKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumatJamKerjaTextFieldActionPerformed

    private void sabtuJamKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabtuJamKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabtuJamKerjaTextFieldActionPerformed

    private void mingguJamKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mingguJamKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mingguJamKerjaTextFieldActionPerformed

    private void jamKerjaBiasaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamKerjaBiasaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamKerjaBiasaTextFieldActionPerformed

    private void dipakaiSndriNegatifRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dipakaiSndriNegatifRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dipakaiSndriNegatifRadioButton1ActionPerformed

    private void upahUangTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upahUangTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upahUangTextFieldActionPerformed

    private void upahBarangTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upahBarangTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upahBarangTextFieldActionPerformed

    private void tidakTahuJamKesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamKesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamKesRadioButtonActionPerformed

    private void tidakJamKesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamKesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamKesRadioButtonActionPerformed

    private void yaJamKesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamKesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamKesRadioButtonActionPerformed

    private void tidakTahuJamKecKerjaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamKecKerjaRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamKecKerjaRadioButton1ActionPerformed

    private void tidakJamKecKerjaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamKecKerjaRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamKecKerjaRadioButton1ActionPerformed

    private void yaJamKecKerjaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamKecKerjaRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamKecKerjaRadioButton1ActionPerformed

    private void tidakTahuJamTuaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamTuaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamTuaRadioButtonActionPerformed

    private void tidakJamTuaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamTuaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamTuaRadioButtonActionPerformed

    private void yaJamTuaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamTuaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamTuaRadioButtonActionPerformed

    private void tidakTahuJamPensRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamPensRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamPensRadioButtonActionPerformed

    private void tidakJamPensRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamPensRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamPensRadioButtonActionPerformed

    private void yaJamPensRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamPensRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamPensRadioButtonActionPerformed

    private void tidakTahuJamMatiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamMatiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamMatiRadioButtonActionPerformed

    private void tidakJamMatiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamMatiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamMatiRadioButtonActionPerformed

    private void yaJamMatiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamMatiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamMatiRadioButtonActionPerformed

    private void tidakTahuCutiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuCutiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuCutiRadioButtonActionPerformed

    private void tidakCutiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakCutiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakCutiRadioButtonActionPerformed

    private void yaCutiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaCutiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaCutiRadioButtonActionPerformed

    private void tidakTahuPesangonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuPesangonRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuPesangonRadioButtonActionPerformed

    private void tidakPesangonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakPesangonRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakPesangonRadioButtonActionPerformed

    private void yaPesangonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaPesangonRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaPesangonRadioButtonActionPerformed

    private void tidakTahuJamKesRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamKesRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamKesRadioButton1ActionPerformed

    private void tidakJamKesRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamKesRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamKesRadioButton1ActionPerformed

    private void yaJamKesRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamKesRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamKesRadioButton1ActionPerformed

    private void kabKotaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabKotaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kabKotaTextFieldActionPerformed

    private void jarakTempatKerjaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarakTempatKerjaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jarakTempatKerjaComboBoxActionPerformed

    private void lamaJalanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaJalanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaJalanComboBoxActionPerformed

    private void jenisTransportComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisTransportComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisTransportComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> caraPembukuanComboBox;
    private javax.swing.ButtonGroup cutiButtonGroup;
    private javax.swing.JRadioButton dipakaiSndriNegatifRadioButton1;
    private javax.swing.JRadioButton dipakaiSndriPositifRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup jamKecKerjaButtonGroup;
    private javax.swing.JTextField jamKerjaBiasaTextField;
    private javax.swing.ButtonGroup jamKesButtonGroup;
    private javax.swing.ButtonGroup jamMatiButtonGroup;
    private javax.swing.ButtonGroup jamPensButtonGroup;
    private javax.swing.ButtonGroup jamTuaButtonGroup;
    private javax.swing.JComboBox<String> jarakTempatKerjaComboBox;
    private javax.swing.JComboBox<String> jenisInstansiComboBox;
    private javax.swing.JTextField jenisKerjaUtmTextField;
    private javax.swing.JComboBox<String> jenisTransportComboBox;
    private javax.swing.JLabel judulDPanel;
    private javax.swing.JTextField jumatJamKerjaTextField;
    private javax.swing.JTextField kabKotaTextField;
    private javax.swing.JTextField kamisJamKerjaTextField;
    private javax.swing.JTextField lainyaInstansiTextField;
    private javax.swing.JComboBox<String> lamaJalanComboBox;
    private javax.swing.JTextField lamaKerjaUtmTextField;
    private javax.swing.JTextField lamaKerjaUtmTextField1;
    private javax.swing.JTextField lapanganKerjaUtmTextField;
    private javax.swing.JTextField mingguJamKerjaTextField;
    private javax.swing.ButtonGroup pakaiSndiriButtonGroup;
    private javax.swing.ButtonGroup pesangonButtonGroup;
    private javax.swing.JTextField provNegTextField;
    private javax.swing.JTextField rabuJamKerjaTextField;
    private javax.swing.JTextField sabtuJamKerjaTextField;
    private javax.swing.JTextField selasaJamKerjaTextField;
    private javax.swing.JTextField seninJamKerjaTextField;
    private javax.swing.ButtonGroup serikatKerjaButtonGroup;
    private javax.swing.JRadioButton setiapBulanRadioButton;
    private javax.swing.JRadioButton setiapHariRadioButton;
    private javax.swing.JRadioButton setiapMingguRadioButton;
    private javax.swing.JComboBox<String> sistemPmbayaranComboBox;
    private javax.swing.JComboBox<String> sistemPmbayaranComboBox1;
    private javax.swing.JComboBox<String> statusKedudukanKerjaComboBox;
    private javax.swing.JComboBox<String> tempatKerjaComboBox;
    private javax.swing.JRadioButton tidakCutiRadioButton;
    private javax.swing.JRadioButton tidakJamKecKerjaRadioButton1;
    private javax.swing.JRadioButton tidakJamKesRadioButton;
    private javax.swing.JRadioButton tidakJamKesRadioButton1;
    private javax.swing.JRadioButton tidakJamMatiRadioButton;
    private javax.swing.JRadioButton tidakJamPensRadioButton;
    private javax.swing.JRadioButton tidakJamTuaRadioButton;
    private javax.swing.JRadioButton tidakPesangonRadioButton;
    private javax.swing.JRadioButton tidakTahuCutiRadioButton;
    private javax.swing.JRadioButton tidakTahuJamKecKerjaRadioButton1;
    private javax.swing.JRadioButton tidakTahuJamKesRadioButton;
    private javax.swing.JRadioButton tidakTahuJamKesRadioButton1;
    private javax.swing.JRadioButton tidakTahuJamMatiRadioButton;
    private javax.swing.JRadioButton tidakTahuJamPensRadioButton;
    private javax.swing.JRadioButton tidakTahuJamTuaRadioButton;
    private javax.swing.JRadioButton tidakTahuPesangonRadioButton;
    private javax.swing.JTextField upahBarangTextField;
    private javax.swing.JTextField upahUangTextField;
    private javax.swing.JRadioButton yaCutiRadioButton;
    private javax.swing.JRadioButton yaJamKecKerjaRadioButton1;
    private javax.swing.JRadioButton yaJamKesRadioButton;
    private javax.swing.JRadioButton yaJamKesRadioButton1;
    private javax.swing.JRadioButton yaJamMatiRadioButton;
    private javax.swing.JRadioButton yaJamPensRadioButton;
    private javax.swing.JRadioButton yaJamTuaRadioButton;
    private javax.swing.JRadioButton yaPesangonRadioButton;
    // End of variables declaration//GEN-END:variables
}
