/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_7_oop.Panel;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JScrollPane;
import kelompok_7_oop.Kelas.AnggotaRuta;
import kelompok_7_oop.Kelas.FasilitasPekerjaan;
import kelompok_7_oop.Kelas.JamKerja;
import kelompok_7_oop.Kelas.Lokasi;
import kelompok_7_oop.Kelas.Pekerjaan;

/**
 *
 * @author Nashir
 */
public class PekerjaanUtamaPanel extends javax.swing.JPanel {

    Pekerjaan pekerjaanUtama = new Pekerjaan();
    JScrollPane mainScrollPane;
    AnggotaRuta art;

    public PekerjaanUtamaPanel(JScrollPane mainJScrollPane, AnggotaRuta art) {
        initComponents();
        this.mainScrollPane = mainJScrollPane;
        this.art = art;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String getSelected(ButtonGroup bg) {
        for (Enumeration<AbstractButton> buttons = bg.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "tidak valid";
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pakaiSndiriButtonGroup = new javax.swing.ButtonGroup();
        jamKesButtonGroup = new javax.swing.ButtonGroup();
        jamKecKerjaButtonGroup = new javax.swing.ButtonGroup();
        jamTuaButtonGroup = new javax.swing.ButtonGroup();
        jamPensButtonGroup = new javax.swing.ButtonGroup();
        jamMatiButtonGroup = new javax.swing.ButtonGroup();
        cutiButtonGroup = new javax.swing.ButtonGroup();
        pesangonButtonGroup = new javax.swing.ButtonGroup();
        serikatKerjaButtonGroup = new javax.swing.ButtonGroup();
        frekuensiKerjaButtonGroup = new javax.swing.ButtonGroup();
        tidakTahuJamKesRadioButton = new javax.swing.JRadioButton();
        yaJamKesRadioButton = new javax.swing.JRadioButton();
        tidakJamKesRadioButton = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        tidakTahuJamKecKerjaRadioButton1 = new javax.swing.JRadioButton();
        tidakJamKecKerjaRadioButton1 = new javax.swing.JRadioButton();
        yaJamKecKerjaRadioButton1 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        tidakTahuJamTuaRadioButton = new javax.swing.JRadioButton();
        tidakJamTuaRadioButton = new javax.swing.JRadioButton();
        yaJamTuaRadioButton = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        tidakTahuJamPensRadioButton = new javax.swing.JRadioButton();
        tidakJamPensRadioButton = new javax.swing.JRadioButton();
        yaJamPensRadioButton = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        tidakTahuJamMatiRadioButton = new javax.swing.JRadioButton();
        tidakJamMatiRadioButton = new javax.swing.JRadioButton();
        yaJamMatiRadioButton = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        tidakTahuCutiRadioButton = new javax.swing.JRadioButton();
        tidakCutiRadioButton = new javax.swing.JRadioButton();
        yaCutiRadioButton = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        tidakTahuPesangonRadioButton = new javax.swing.JRadioButton();
        tidakPesangonRadioButton = new javax.swing.JRadioButton();
        yaPesangonRadioButton = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        kontrakkerjaComboBox = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        tidakTahuJamKesRadioButton1 = new javax.swing.JRadioButton();
        tidakJamKesRadioButton1 = new javax.swing.JRadioButton();
        yaJamKesRadioButton1 = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        jenisInstansiComboBox = new javax.swing.JComboBox<>();
        lainyaInstansiTextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tempatKerjaComboBox = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        provNegTextField = new javax.swing.JTextField();
        kabKotaTextField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jarakTempatKerjaComboBox = new javax.swing.JComboBox<>();
        setiapHariRadioButton = new javax.swing.JRadioButton();
        setiapMingguRadioButton = new javax.swing.JRadioButton();
        setiapBulanRadioButton = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        lamaJalanComboBox = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jenisTransportComboBox = new javax.swing.JComboBox<>();
        PekerjaanUtamaButton = new javax.swing.JButton();
        lamaBekerjaSpinner = new javax.swing.JSpinner();
        lamaCariKerjaSpinner = new javax.swing.JSpinner();
        seninJamKerjaSpinner = new javax.swing.JSpinner();
        selasaJamKerjaSpinner = new javax.swing.JSpinner();
        PekerjaanTambahanjLabel = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jenislapanganKerjaTextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jabatanKerjaTextField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        rabuJamKerjaSpinner = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();
        kamisJamKerjaSpinner = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        jumatJamKerjaSpinner = new javax.swing.JSpinner();
        jLabel48 = new javax.swing.JLabel();
        sabtuJamKerjaSpinner = new javax.swing.JSpinner();
        jLabel49 = new javax.swing.JLabel();
        mingguJamKerjaSpinner = new javax.swing.JSpinner();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jamKerjaBiasaSpinner = new javax.swing.JSpinner();
        jLabel52 = new javax.swing.JLabel();
        statusKedudukanComboBox = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        pembukuanPerusahaanComboBox = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        yaJamKesRadioButton2 = new javax.swing.JRadioButton();
        tidakJamKesRadioButton2 = new javax.swing.JRadioButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        upahUangTextField = new javax.swing.JTextField();
        upahBarangTextField = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        sistemPembayaranComboBox = new javax.swing.JComboBox<>();
        jLabel59 = new javax.swing.JLabel();

        jLabel1.setText("Selama seminggu lalu anda mencair kerja:");

        jamKesButtonGroup.add(tidakTahuJamKesRadioButton);
        tidakTahuJamKesRadioButton.setText("Tidak tahu");
        tidakTahuJamKesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamKesRadioButtonActionPerformed(evt);
            }
        });

        jamKesButtonGroup.add(yaJamKesRadioButton);
        yaJamKesRadioButton.setText("Ya");
        yaJamKesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamKesRadioButtonActionPerformed(evt);
            }
        });

        jamKesButtonGroup.add(tidakJamKesRadioButton);
        tidakJamKesRadioButton.setText("Tidak");
        tidakJamKesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamKesRadioButtonActionPerformed(evt);
            }
        });

        jLabel23.setText("Jaminan kesehatan");

        jamKecKerjaButtonGroup.add(tidakTahuJamKecKerjaRadioButton1);
        tidakTahuJamKecKerjaRadioButton1.setText("Tidak tahu");
        tidakTahuJamKecKerjaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamKecKerjaRadioButton1ActionPerformed(evt);
            }
        });

        jamKecKerjaButtonGroup.add(tidakJamKecKerjaRadioButton1);
        tidakJamKecKerjaRadioButton1.setText("Tidak");
        tidakJamKecKerjaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamKecKerjaRadioButton1ActionPerformed(evt);
            }
        });

        jamKecKerjaButtonGroup.add(yaJamKecKerjaRadioButton1);
        yaJamKecKerjaRadioButton1.setText("Ya");
        yaJamKecKerjaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamKecKerjaRadioButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Jaminan kecelakaan kerja");

        jamTuaButtonGroup.add(tidakTahuJamTuaRadioButton);
        tidakTahuJamTuaRadioButton.setText("Tidak tahu");
        tidakTahuJamTuaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamTuaRadioButtonActionPerformed(evt);
            }
        });

        jamTuaButtonGroup.add(tidakJamTuaRadioButton);
        tidakJamTuaRadioButton.setText("Tidak");
        tidakJamTuaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamTuaRadioButtonActionPerformed(evt);
            }
        });

        jamTuaButtonGroup.add(yaJamTuaRadioButton);
        yaJamTuaRadioButton.setText("Ya");
        yaJamTuaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamTuaRadioButtonActionPerformed(evt);
            }
        });

        jLabel25.setText("Jaminan hari tua");

        jamPensButtonGroup.add(tidakTahuJamPensRadioButton);
        tidakTahuJamPensRadioButton.setText("Tidak tahu");
        tidakTahuJamPensRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamPensRadioButtonActionPerformed(evt);
            }
        });

        jamPensButtonGroup.add(tidakJamPensRadioButton);
        tidakJamPensRadioButton.setText("Tidak");
        tidakJamPensRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamPensRadioButtonActionPerformed(evt);
            }
        });

        jamPensButtonGroup.add(yaJamPensRadioButton);
        yaJamPensRadioButton.setText("Ya");
        yaJamPensRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamPensRadioButtonActionPerformed(evt);
            }
        });

        jLabel26.setText("Jaminan pensiun");

        jamMatiButtonGroup.add(tidakTahuJamMatiRadioButton);
        tidakTahuJamMatiRadioButton.setText("Tidak tahu");
        tidakTahuJamMatiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamMatiRadioButtonActionPerformed(evt);
            }
        });

        jamMatiButtonGroup.add(tidakJamMatiRadioButton);
        tidakJamMatiRadioButton.setText("Tidak");
        tidakJamMatiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamMatiRadioButtonActionPerformed(evt);
            }
        });

        jamMatiButtonGroup.add(yaJamMatiRadioButton);
        yaJamMatiRadioButton.setText("Ya");
        yaJamMatiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamMatiRadioButtonActionPerformed(evt);
            }
        });

        jLabel27.setText("Jaminan kematian");

        cutiButtonGroup.add(tidakTahuCutiRadioButton);
        tidakTahuCutiRadioButton.setText("Tidak tahu");
        tidakTahuCutiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuCutiRadioButtonActionPerformed(evt);
            }
        });

        cutiButtonGroup.add(tidakCutiRadioButton);
        tidakCutiRadioButton.setText("Tidak");
        tidakCutiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakCutiRadioButtonActionPerformed(evt);
            }
        });

        cutiButtonGroup.add(yaCutiRadioButton);
        yaCutiRadioButton.setText("Ya");
        yaCutiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaCutiRadioButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Cuti tanpa potong upah");

        pesangonButtonGroup.add(tidakTahuPesangonRadioButton);
        tidakTahuPesangonRadioButton.setText("Tidak tahu");
        tidakTahuPesangonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuPesangonRadioButtonActionPerformed(evt);
            }
        });

        pesangonButtonGroup.add(tidakPesangonRadioButton);
        tidakPesangonRadioButton.setText("Tidak");
        tidakPesangonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakPesangonRadioButtonActionPerformed(evt);
            }
        });

        pesangonButtonGroup.add(yaPesangonRadioButton);
        yaPesangonRadioButton.setText("Ya");
        yaPesangonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaPesangonRadioButtonActionPerformed(evt);
            }
        });

        jLabel29.setText("Pesangon");

        jLabel30.setText("Jenis perjanjian atau kontrak kerja:");

        kontrakkerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perjanjian Kerja Waktu Tidak Tertentu", "Perjanjian Kerja Waktu Tertentu", "Perjanjian Lisan", "Tidak ada perjanjian/kontrak kerja", "Tidak tahu" }));
        kontrakkerjaComboBox.setSelectedIndex(-1);

        jLabel31.setText("Terlibat dalam serikat pekerja:");

        serikatKerjaButtonGroup.add(tidakTahuJamKesRadioButton1);
        tidakTahuJamKesRadioButton1.setText("Tidak tahu");
        tidakTahuJamKesRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakTahuJamKesRadioButton1ActionPerformed(evt);
            }
        });

        serikatKerjaButtonGroup.add(tidakJamKesRadioButton1);
        tidakJamKesRadioButton1.setText("Tidak");
        tidakJamKesRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamKesRadioButton1ActionPerformed(evt);
            }
        });

        serikatKerjaButtonGroup.add(yaJamKesRadioButton1);
        yaJamKesRadioButton1.setText("Ya");
        yaJamKesRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamKesRadioButton1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Jenis instansi/lembaga/institusi dari tempat kerja/usaha:");

        jenisInstansiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemerintah/negeri", "Lembaga/organisasi internasional", "Lembaga nonprofit/nirlaba", "Lembaga profit (perusahaan swasta, BUMN, BUMD)", "Koperasi", "Usaha perorangan/usaha rumah tangga", "Rumah tangga", "Lainnya", "Tidak tahu" }));
        jenisInstansiComboBox.setSelectedIndex(-1);

        lainyaInstansiTextField.setEditable(false);

        jLabel33.setText("Lokasi utama tempat kerja:");

        tempatKerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rumah sendiri  ", "Rumah keluarga/teman", "Rumah pemberi kerja", "Lainnya" }));
        tempatKerjaComboBox.setSelectedIndex(-1);

        jLabel34.setText("Letak tempat kerja:");

        kabKotaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabKotaTextFieldActionPerformed(evt);
            }
        });

        jLabel35.setText("Pulang/pergi tempat kerja:");

        jLabel36.setText("Jarak rumah ke tempat kerja:");

        jarakTempatKerjaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< 10 Km", "10 – 29 Km", "≥ 30 Km", "Tidak tahu" }));
        jarakTempatKerjaComboBox.setSelectedIndex(-1);
        jarakTempatKerjaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarakTempatKerjaComboBoxActionPerformed(evt);
            }
        });

        frekuensiKerjaButtonGroup.add(setiapHariRadioButton);
        setiapHariRadioButton.setText("Setiap Hari");

        frekuensiKerjaButtonGroup.add(setiapMingguRadioButton);
        setiapMingguRadioButton.setText("Setiap Minggu");

        frekuensiKerjaButtonGroup.add(setiapBulanRadioButton);
        setiapBulanRadioButton.setText("Setiap Bulan");

        jLabel37.setText("Lama perjalanan ke tempat kerja:");

        lamaJalanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤ 30 Menit", "31 – 60 Menit", "61 – 120 Menit", "> 120 Menit" }));
        lamaJalanComboBox.setSelectedIndex(-1);
        lamaJalanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaJalanComboBoxActionPerformed(evt);
            }
        });

        jLabel38.setText("Jenis transportasi ke tempat kerja:");

        jenisTransportComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transportasi umum", "Transportasi bersama", "Transportasi pribadi", "Jalan kaki" }));
        jenisTransportComboBox.setSelectedIndex(-1);
        jenisTransportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisTransportComboBoxActionPerformed(evt);
            }
        });

        PekerjaanUtamaButton.setText("NEXT");
        PekerjaanUtamaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PekerjaanUtamaButtonActionPerformed(evt);
            }
        });

        PekerjaanTambahanjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PekerjaanTambahanjLabel.setText("V.D. PEKERJAAN UTAMA");

        jLabel39.setText("Jenis lapangan usaha pekerjaan utama seminggu lalu:");

        jenislapanganKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenislapanganKerjaTextFieldActionPerformed(evt);
            }
        });

        jLabel40.setText("Jabatan dari pekerjaan utama selama seminggu lalu:");

        jabatanKerjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanKerjaTextFieldActionPerformed(evt);
            }
        });

        jLabel41.setText("Lama bekerja di pekerjaan utama:");

        jLabel42.setText("Lama mencari kerja/mempersiapkan usaha pekerjaan utama:");

        jLabel43.setText("Jam kerja unutk pekerjaan utama selama seminggu lalu:");

        jLabel44.setText("Senin");

        jLabel45.setText("Selasa");

        jLabel46.setText("Rabu");

        jLabel47.setText("Kamis");

        jLabel48.setText("Jum'at");

        jLabel49.setText("Sabtu");

        jLabel50.setText("Minggu");

        jLabel51.setText("Jumlah jam kerja biasa dalam seminggu:");

        jLabel52.setText("Status kedudukan dalam pekerjaan utama:");

        statusKedudukanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berusaha sendiri", "Berusaha dibantu buruh tidak tetap/tidak dibayar", "Berusaha dibantu buruh tetap/dibayar", "Buruh/karyawan/pegawa", "Pekerja bebas di pertanian", "Pekerja bebas di nonpertanian", "Pekerja keluarga/tidak dibayar" }));

        jLabel53.setText("Pembukuan perusahaan:");

        pembukuanPerusahaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak ada pembukuan tertulis", "Ada, pembukuan sederhana", "Berusaha dibantu buruh tetap/dibayar", "Pembukuan lengkap ", "Tidak tahu" }));
        pembukuanPerusahaanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembukuanPerusahaanComboBoxActionPerformed(evt);
            }
        });

        jLabel54.setText("Hasil barang/jasa usaha diutamakan digunakan sendiri:");

        pakaiSndiriButtonGroup.add(yaJamKesRadioButton2);
        yaJamKesRadioButton2.setText("Ya");
        yaJamKesRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaJamKesRadioButton2ActionPerformed(evt);
            }
        });

        pakaiSndiriButtonGroup.add(tidakJamKesRadioButton2);
        tidakJamKesRadioButton2.setText("Tidak");
        tidakJamKesRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakJamKesRadioButton2ActionPerformed(evt);
            }
        });

        jLabel55.setText("Upah/Gaji bersih dari pekerjaan utama selama sebualan lalu:");

        jLabel56.setText("Uang:");

        jLabel57.setText("Barang:");

        upahUangTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upahUangTextFieldActionPerformed(evt);
            }
        });

        upahBarangTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upahBarangTextFieldActionPerformed(evt);
            }
        });

        jLabel58.setText("Sistem pembayaran upah dari pekerjaan utama:");

        sistemPembayaranComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulanan", "Mingguan", "Harian", "Borongan", "Dibayar per satuan hasil" }));
        sistemPembayaranComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemPembayaranComboBoxActionPerformed(evt);
            }
        });

        jLabel59.setText("Fasilitas perusahaan:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PekerjaanUtamaButton)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(sistemPembayaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jenisTransportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lamaJalanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jarakTempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(setiapHariRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(setiapMingguRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(setiapBulanRadioButton))
                                        .addComponent(tempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jenisInstansiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(yaJamKesRadioButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tidakJamKesRadioButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tidakTahuJamKesRadioButton1))
                                        .addComponent(kontrakkerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(196, 196, 196)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(yaJamKesRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakJamKesRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakTahuJamKesRadioButton))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(yaJamKecKerjaRadioButton1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakJamKecKerjaRadioButton1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakTahuJamKecKerjaRadioButton1))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(yaJamTuaRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakJamTuaRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakTahuJamTuaRadioButton))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(yaJamPensRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakJamPensRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakTahuJamPensRadioButton))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(yaJamMatiRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakJamMatiRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakTahuJamMatiRadioButton))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(yaCutiRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakCutiRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakTahuCutiRadioButton))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(yaPesangonRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakPesangonRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tidakTahuPesangonRadioButton))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(provNegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lainyaInstansiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lamaBekerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lamaCariKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(PekerjaanTambahanjLabel)
                                            .addGap(89, 89, 89))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jabatanKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jenislapanganKerjaTextField))
                                            .addGap(86, 86, 86)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(yaJamKesRadioButton2)
                                                .addGap(18, 18, 18)
                                                .addComponent(tidakJamKesRadioButton2))
                                            .addComponent(pembukuanPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jamKerjaBiasaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel45)
                                                            .addComponent(jLabel46))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(rabuJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(selasaJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(30, 30, 30)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel49)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(sabtuJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel48)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jumatJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel44)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(seninJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(29, 29, 29)
                                                        .addComponent(jLabel47)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(kamisJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel50)
                                                .addGap(18, 18, 18)
                                                .addComponent(mingguJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(statusKedudukanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel56)
                                                    .addComponent(jLabel57))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(upahBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(upahUangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {upahBarangTextField, upahUangTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PekerjaanTambahanjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenislapanganKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jabatanKerjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamaBekerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamaCariKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel50)
                    .addComponent(mingguJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(kamisJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seninJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(selasaJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(jumatJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel49)
                    .addComponent(sabtuJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rabuJamKerjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jamKerjaBiasaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusKedudukanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembukuanPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yaJamKesRadioButton2)
                    .addComponent(tidakJamKesRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel55)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(upahUangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel57))
                    .addComponent(upahBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sistemPembayaranComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel59)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(yaJamKesRadioButton)
                    .addComponent(tidakJamKesRadioButton)
                    .addComponent(tidakTahuJamKesRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(yaJamKecKerjaRadioButton1)
                    .addComponent(tidakJamKecKerjaRadioButton1)
                    .addComponent(tidakTahuJamKecKerjaRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(yaJamTuaRadioButton)
                    .addComponent(tidakJamTuaRadioButton)
                    .addComponent(tidakTahuJamTuaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(yaJamPensRadioButton)
                    .addComponent(tidakJamPensRadioButton)
                    .addComponent(tidakTahuJamPensRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(yaJamMatiRadioButton)
                    .addComponent(tidakJamMatiRadioButton)
                    .addComponent(tidakTahuJamMatiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(yaCutiRadioButton)
                    .addComponent(tidakCutiRadioButton)
                    .addComponent(tidakTahuCutiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(yaPesangonRadioButton)
                    .addComponent(tidakPesangonRadioButton)
                    .addComponent(tidakTahuPesangonRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kontrakkerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yaJamKesRadioButton1)
                    .addComponent(tidakJamKesRadioButton1)
                    .addComponent(tidakTahuJamKesRadioButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisInstansiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainyaInstansiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provNegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setiapHariRadioButton)
                    .addComponent(setiapMingguRadioButton)
                    .addComponent(setiapBulanRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jarakTempatKerjaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lamaJalanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisTransportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PekerjaanUtamaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tidakTahuJamKesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamKesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamKesRadioButtonActionPerformed

    private void tidakJamKesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamKesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamKesRadioButtonActionPerformed

    private void yaJamKesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamKesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamKesRadioButtonActionPerformed

    private void tidakTahuJamKecKerjaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamKecKerjaRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamKecKerjaRadioButton1ActionPerformed

    private void tidakJamKecKerjaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamKecKerjaRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamKecKerjaRadioButton1ActionPerformed

    private void yaJamKecKerjaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamKecKerjaRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamKecKerjaRadioButton1ActionPerformed

    private void tidakTahuJamTuaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamTuaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamTuaRadioButtonActionPerformed

    private void tidakJamTuaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamTuaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamTuaRadioButtonActionPerformed

    private void yaJamTuaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamTuaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamTuaRadioButtonActionPerformed

    private void tidakTahuJamPensRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamPensRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamPensRadioButtonActionPerformed

    private void tidakJamPensRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamPensRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamPensRadioButtonActionPerformed

    private void yaJamPensRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamPensRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamPensRadioButtonActionPerformed

    private void tidakTahuJamMatiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamMatiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamMatiRadioButtonActionPerformed

    private void tidakJamMatiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamMatiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamMatiRadioButtonActionPerformed

    private void yaJamMatiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamMatiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamMatiRadioButtonActionPerformed

    private void tidakTahuCutiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuCutiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuCutiRadioButtonActionPerformed

    private void tidakCutiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakCutiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakCutiRadioButtonActionPerformed

    private void yaCutiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaCutiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaCutiRadioButtonActionPerformed

    private void tidakTahuPesangonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuPesangonRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuPesangonRadioButtonActionPerformed

    private void tidakPesangonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakPesangonRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakPesangonRadioButtonActionPerformed

    private void yaPesangonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaPesangonRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaPesangonRadioButtonActionPerformed

    private void tidakTahuJamKesRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakTahuJamKesRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakTahuJamKesRadioButton1ActionPerformed

    private void tidakJamKesRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamKesRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamKesRadioButton1ActionPerformed

    private void yaJamKesRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamKesRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamKesRadioButton1ActionPerformed

    private void kabKotaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabKotaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kabKotaTextFieldActionPerformed

    private void jarakTempatKerjaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarakTempatKerjaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jarakTempatKerjaComboBoxActionPerformed

    private void lamaJalanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaJalanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaJalanComboBoxActionPerformed

    private void jenisTransportComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisTransportComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisTransportComboBoxActionPerformed

    private void PekerjaanUtamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PekerjaanUtamaButtonActionPerformed

        Lokasi lokasi = new Lokasi();
        lokasi.setNegaraAtauProv(provNegTextField.getText());
        lokasi.setKabKota(kabKotaTextField.getText());

        pekerjaanUtama.setTempatKerja(lokasi);
        pekerjaanUtama.setJenisPekerjaan(jenislapanganKerjaTextField.getText());
        pekerjaanUtama.setJabatan(jabatanKerjaTextField.getText());
        pekerjaanUtama.setLamaBekerja(Integer.parseInt(lamaBekerjaSpinner.getValue().toString()));
        pekerjaanUtama.setLamaMencari(Integer.parseInt(lamaCariKerjaSpinner.getValue().toString()));

        JamKerja jamKerja = new JamKerja();
        int jam[] = new int[7];
        jam[0] = Integer.parseInt(seninJamKerjaSpinner.getValue().toString());
        jam[1] = Integer.parseInt(selasaJamKerjaSpinner.getValue().toString());
        jam[2] = Integer.parseInt(rabuJamKerjaSpinner.getValue().toString());
        jam[3] = Integer.parseInt(kamisJamKerjaSpinner.getValue().toString());
        jam[4] = Integer.parseInt(jumatJamKerjaSpinner.getValue().toString());
        jam[5] = Integer.parseInt(sabtuJamKerjaSpinner.getValue().toString());
        jam[6] = Integer.parseInt(mingguJamKerjaSpinner.getValue().toString());

        jamKerja.setJamKerjaPerHari(jam);

        jamKerja.setJamKerjaBiasa(Integer.parseInt(jamKerjaBiasaSpinner.getValue().toString()));
        pekerjaanUtama.setJamkerja(jamKerja);
        pekerjaanUtama.setStatusPekerjaan(statusKedudukanComboBox.getSelectedItem().toString());
        pekerjaanUtama.setCaraPembukuan(pembukuanPerusahaanComboBox.getSelectedItem().toString());
        pekerjaanUtama.setSistemPengupahan(sistemPembayaranComboBox.getSelectedItem().toString());

        FasilitasPekerjaan layananPerusahaan = new FasilitasPekerjaan();

        layananPerusahaan.setJaminanHariTua(getSelected(jamTuaButtonGroup));
        layananPerusahaan.setJaminanKecelakaanKerja(getSelected(jamKecKerjaButtonGroup));
        layananPerusahaan.setJaminanKematian(getSelected(jamMatiButtonGroup));
        layananPerusahaan.setJaminanKesehatan(getSelected(jamKesButtonGroup));
        layananPerusahaan.setJaminanPensiun(getSelected(jamPensButtonGroup));
        layananPerusahaan.setCuti(getSelected(cutiButtonGroup));
        layananPerusahaan.setPesangon(getSelected(pesangonButtonGroup));
        
        pekerjaanUtama.setLayananPerusahaan(layananPerusahaan);
        
        pekerjaanUtama.setPerjanjianKerja(kontrakkerjaComboBox.getSelectedItem().toString());

        pekerjaanUtama.setSerikatPekerja(getSelected(serikatKerjaButtonGroup));
        pekerjaanUtama.setJenisInstansi(jenisInstansiComboBox.getSelectedItem().toString());
        pekerjaanUtama.setLokasiUtamaKerja(tempatKerjaComboBox.getSelectedItem().toString());
        pekerjaanUtama.setFrekuensiPergiKerja(getSelected(frekuensiKerjaButtonGroup));
        pekerjaanUtama.setJarak(jarakTempatKerjaComboBox.getSelectedItem().toString());
        pekerjaanUtama.setLamaPerjalanan(lamaJalanComboBox.getSelectedItem().toString());
        pekerjaanUtama.setJenisTransportasi(jenisTransportComboBox.getSelectedItem().toString());
        
        mainScrollPane.setViewportView(new PekerjaanTambahanPanel(mainScrollPane, art));
    }//GEN-LAST:event_PekerjaanUtamaButtonActionPerformed

    private void jenislapanganKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenislapanganKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenislapanganKerjaTextFieldActionPerformed

    private void jabatanKerjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanKerjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanKerjaTextFieldActionPerformed

    private void pembukuanPerusahaanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembukuanPerusahaanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembukuanPerusahaanComboBoxActionPerformed

    private void yaJamKesRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaJamKesRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaJamKesRadioButton2ActionPerformed

    private void tidakJamKesRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakJamKesRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakJamKesRadioButton2ActionPerformed

    private void upahUangTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upahUangTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upahUangTextFieldActionPerformed

    private void upahBarangTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upahBarangTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upahBarangTextFieldActionPerformed

    private void sistemPembayaranComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemPembayaranComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sistemPembayaranComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PekerjaanTambahanjLabel;
    private javax.swing.JButton PekerjaanUtamaButton;
    private javax.swing.ButtonGroup cutiButtonGroup;
    private javax.swing.ButtonGroup frekuensiKerjaButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JTextField jabatanKerjaTextField;
    private javax.swing.ButtonGroup jamKecKerjaButtonGroup;
    private javax.swing.JSpinner jamKerjaBiasaSpinner;
    private javax.swing.ButtonGroup jamKesButtonGroup;
    private javax.swing.ButtonGroup jamMatiButtonGroup;
    private javax.swing.ButtonGroup jamPensButtonGroup;
    private javax.swing.ButtonGroup jamTuaButtonGroup;
    private javax.swing.JComboBox<String> jarakTempatKerjaComboBox;
    private javax.swing.JComboBox<String> jenisInstansiComboBox;
    private javax.swing.JComboBox<String> jenisTransportComboBox;
    private javax.swing.JTextField jenislapanganKerjaTextField;
    private javax.swing.JSpinner jumatJamKerjaSpinner;
    private javax.swing.JTextField kabKotaTextField;
    private javax.swing.JSpinner kamisJamKerjaSpinner;
    private javax.swing.JComboBox<String> kontrakkerjaComboBox;
    private javax.swing.JTextField lainyaInstansiTextField;
    private javax.swing.JSpinner lamaBekerjaSpinner;
    private javax.swing.JSpinner lamaCariKerjaSpinner;
    private javax.swing.JComboBox<String> lamaJalanComboBox;
    private javax.swing.JSpinner mingguJamKerjaSpinner;
    private javax.swing.ButtonGroup pakaiSndiriButtonGroup;
    private javax.swing.JComboBox<String> pembukuanPerusahaanComboBox;
    private javax.swing.ButtonGroup pesangonButtonGroup;
    private javax.swing.JTextField provNegTextField;
    private javax.swing.JSpinner rabuJamKerjaSpinner;
    private javax.swing.JSpinner sabtuJamKerjaSpinner;
    private javax.swing.JSpinner selasaJamKerjaSpinner;
    private javax.swing.JSpinner seninJamKerjaSpinner;
    private javax.swing.ButtonGroup serikatKerjaButtonGroup;
    private javax.swing.JRadioButton setiapBulanRadioButton;
    private javax.swing.JRadioButton setiapHariRadioButton;
    private javax.swing.JRadioButton setiapMingguRadioButton;
    private javax.swing.JComboBox<String> sistemPembayaranComboBox;
    private javax.swing.JComboBox<String> statusKedudukanComboBox;
    private javax.swing.JComboBox<String> tempatKerjaComboBox;
    private javax.swing.JRadioButton tidakCutiRadioButton;
    private javax.swing.JRadioButton tidakJamKecKerjaRadioButton1;
    private javax.swing.JRadioButton tidakJamKesRadioButton;
    private javax.swing.JRadioButton tidakJamKesRadioButton1;
    private javax.swing.JRadioButton tidakJamKesRadioButton2;
    private javax.swing.JRadioButton tidakJamMatiRadioButton;
    private javax.swing.JRadioButton tidakJamPensRadioButton;
    private javax.swing.JRadioButton tidakJamTuaRadioButton;
    private javax.swing.JRadioButton tidakPesangonRadioButton;
    private javax.swing.JRadioButton tidakTahuCutiRadioButton;
    private javax.swing.JRadioButton tidakTahuJamKecKerjaRadioButton1;
    private javax.swing.JRadioButton tidakTahuJamKesRadioButton;
    private javax.swing.JRadioButton tidakTahuJamKesRadioButton1;
    private javax.swing.JRadioButton tidakTahuJamMatiRadioButton;
    private javax.swing.JRadioButton tidakTahuJamPensRadioButton;
    private javax.swing.JRadioButton tidakTahuJamTuaRadioButton;
    private javax.swing.JRadioButton tidakTahuPesangonRadioButton;
    private javax.swing.JTextField upahBarangTextField;
    private javax.swing.JTextField upahUangTextField;
    private javax.swing.JRadioButton yaCutiRadioButton;
    private javax.swing.JRadioButton yaJamKecKerjaRadioButton1;
    private javax.swing.JRadioButton yaJamKesRadioButton;
    private javax.swing.JRadioButton yaJamKesRadioButton1;
    private javax.swing.JRadioButton yaJamKesRadioButton2;
    private javax.swing.JRadioButton yaJamMatiRadioButton;
    private javax.swing.JRadioButton yaJamPensRadioButton;
    private javax.swing.JRadioButton yaJamTuaRadioButton;
    private javax.swing.JRadioButton yaPesangonRadioButton;
    // End of variables declaration//GEN-END:variables
}
