/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_7_oop.Panel;

/**
 *
 * @author maya
 */
public class PekerjaanTambahanPanel extends javax.swing.JPanel {

    /**
     * Creates new form PekerjaanTambahanPanel
     */
    public PekerjaanTambahanPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PekerjaanTambahanjLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        positifRadioButton = new javax.swing.JRadioButton();
        negatifRadioButton = new javax.swing.JRadioButton();
        PekerjaanTambahanTextField = new javax.swing.JTextField();
        PekerjaanTambahanComboBox = new javax.swing.JComboBox<>();

        PekerjaanTambahanjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PekerjaanTambahanjLabel.setText("V.E. PEKERJAAN TAMBAHAN");

        jLabel2.setText("34 . Apakah  ( NAMA )  selama seminggu yang lalu mempunyai  pekerjaan tambahan ?");

        jLabel3.setText("35 .  Apakah lapangan usaha / bidang  pekerjaan tambahan  utama dari tempat ( NAMA ) bekerja selama seminggu yang lalu ?");

        jLabel4.setText("36 .  Apakah status / kedudukan  ( NAMA )  dalam pekerjaan  tambahan utama ?");

        buttonGroup1.add(positifRadioButton);
        positifRadioButton.setText("YA");
        positifRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positifRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(negatifRadioButton);
        negatifRadioButton.setText("TIDAK");

        PekerjaanTambahanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berusaha sendiri", "Berusaha dibantu buruh tidak tetap/pekerja keluarga/tidak dibayar", "Berusaha dibantu buruh tetap/dibayar", "Buruh/karyawan/pegawai", "Pekerja bebas di pertanian", "Pekerja bebas di nonpertanian", "Pekerja keluarga/tidakdibayar" }));
        PekerjaanTambahanComboBox.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PekerjaanTambahanjLabel)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(positifRadioButton)
                        .addGap(28, 28, 28)
                        .addComponent(negatifRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(PekerjaanTambahanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(PekerjaanTambahanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PekerjaanTambahanjLabel)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positifRadioButton)
                    .addComponent(negatifRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PekerjaanTambahanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(PekerjaanTambahanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void positifRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positifRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positifRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PekerjaanTambahanComboBox;
    private javax.swing.JTextField PekerjaanTambahanTextField;
    private javax.swing.JLabel PekerjaanTambahanjLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton negatifRadioButton;
    private javax.swing.JRadioButton positifRadioButton;
    // End of variables declaration//GEN-END:variables
}
