/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_7_oop.Panel;

import java.awt.GridLayout;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.plaf.IconUIResource;
import kelompok_7_oop.Kelas.Ringkasan;
import kelompok_7_oop.Kelas.Ruta;

/**
 *
 * @author USER-PC
 */
public class PengenalanTempatPanel extends javax.swing.JPanel {

    private JScrollPane mainScrollPane;
    private Ruta ruta = new Ruta();
    private Ringkasan ringkasan=null;

    ;
    /**
     * Creates new form pengenalanTempatPanel
     */
    public PengenalanTempatPanel(JScrollPane mainScrollPane) {
        initComponents();
        this.mainScrollPane = mainScrollPane;

    }

    public AbstractButton getSelected(ButtonGroup bG) {
        for (Enumeration<AbstractButton> buttons = bG.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        provinsiTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        klasifikasiButtonGroup = new javax.swing.ButtonGroup();
        hasilKunjunganButtonGroup = new javax.swing.ButtonGroup();
        judulAPanel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        provinsiTextField = new javax.swing.JTextField();
        kabKotaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        desaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomorBSTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pedesaanRadioButton = new javax.swing.JRadioButton();
        perkotaanRadioButton = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kecamatanTextField = new javax.swing.JTextField();
        nomorKodeSampleTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namaKaRuTaTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pemberiInfoTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        berhasilRadioButton = new javax.swing.JRadioButton();
        tolakRadioButton = new javax.swing.JRadioButton();
        tidakKetemuRadioButton = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        nomorRutaSampleTextField = new javax.swing.JTextField();
        nextButtonPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        provinsiTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinsiTextField6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nomor BS:");

        judulAPanel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judulAPanel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulAPanel1.setText("I. PENGENALAN TEMPAT");

        jLabel1.setText("Provinsi:");

        provinsiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinsiTextFieldActionPerformed(evt);
            }
        });

        kabKotaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabKotaTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Kabupaten/Kota:");

        desaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desaTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Desa/Kelurahan:");

        jLabel5.setText("Klasifikasi desa/kelurahan:");

        nomorBSTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorBSTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Nomor BS:");

        klasifikasiButtonGroup.add(pedesaanRadioButton);
        pedesaanRadioButton.setText("Perdesaan");

        klasifikasiButtonGroup.add(perkotaanRadioButton);
        perkotaanRadioButton.setText("Perkotaan");

        jLabel8.setText("Kecamatan:");

        kecamatanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecamatanTextFieldActionPerformed(evt);
            }
        });

        nomorKodeSampleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorKodeSampleTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Nomor kode sample:");

        jLabel10.setText("Nama kepala rumah tanga:");

        namaKaRuTaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKaRuTaTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama dan nomor urut pemberi info utama:");

        pemberiInfoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemberiInfoTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Hasil kunjungan:");

        hasilKunjunganButtonGroup.add(berhasilRadioButton);
        berhasilRadioButton.setText("Berhasil");

        hasilKunjunganButtonGroup.add(tolakRadioButton);
        tolakRadioButton.setText("Menolak");

        hasilKunjunganButtonGroup.add(tidakKetemuRadioButton);
        tidakKetemuRadioButton.setText("Tidak dapat ditemui");

        jLabel13.setText("Nomor urut Ruta sample:");

        nomorRutaSampleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorRutaSampleTextFieldActionPerformed(evt);
            }
        });

        nextButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonPanelMouseEntered(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nashir\\Desktop\\Next page_48px.png")); // NOI18N

        javax.swing.GroupLayout nextButtonPanelLayout = new javax.swing.GroupLayout(nextButtonPanel);
        nextButtonPanel.setLayout(nextButtonPanelLayout);
        nextButtonPanelLayout.setHorizontalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        nextButtonPanelLayout.setVerticalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(judulAPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kecamatanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nomorKodeSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namaKaRuTaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pedesaanRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(perkotaanRadioButton))
                                            .addComponent(provinsiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(325, 325, 325)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(desaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(nomorBSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel13))
                                        .addComponent(nomorRutaSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(pemberiInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(berhasilRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tolakRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tidakKetemuRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addComponent(jLabel12)))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(nextButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulAPanel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(provinsiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(kecamatanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(desaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pedesaanRadioButton)
                            .addComponent(perkotaanRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(nomorBSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(nomorKodeSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorRutaSampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaKaRuTaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pemberiInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(berhasilRadioButton)
                    .addComponent(tolakRadioButton)
                    .addComponent(tidakKetemuRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void provinsiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinsiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinsiTextFieldActionPerformed

    private void kabKotaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabKotaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kabKotaTextFieldActionPerformed

    private void desaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desaTextFieldActionPerformed

    private void nomorBSTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorBSTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorBSTextFieldActionPerformed

    private void provinsiTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinsiTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinsiTextField6ActionPerformed

    private void kecamatanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecamatanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kecamatanTextFieldActionPerformed

    private void nomorKodeSampleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorKodeSampleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorKodeSampleTextFieldActionPerformed

    private void namaKaRuTaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKaRuTaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKaRuTaTextFieldActionPerformed

    private void pemberiInfoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemberiInfoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemberiInfoTextFieldActionPerformed

    private void nomorRutaSampleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorRutaSampleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorRutaSampleTextFieldActionPerformed

    private void nextButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPanelMouseClicked
        // TODO add your handling code here:
//        
        ruta.getAlamat().setNegaraAtauProv(provinsiTextField.getText());
        ruta.getAlamat().setKabKota(kabKotaTextField.getText());
        ruta.getAlamat().setKecamatan(kecamatanTextField.getText());
        ruta.getAlamat().setDesaAtauKel(desaTextField.getText());
        ruta.getAlamat().setNoBlokSensus(nomorBSTextField.getText());
        ruta.getAlamat().setNoKodeSample(nomorKodeSampleTextField.getText());
        ruta.getAlamat().setNoUrutRtSample(nomorRutaSampleTextField.getText());
        if (getSelected(klasifikasiButtonGroup)!=null){
            ruta.getAlamat().setKlasifikasiDesa(getSelected(klasifikasiButtonGroup).getText());
            
        }
        ruta.setNamaKepalaRT(namaKaRuTaTextField.getText());
        ruta.setNoUrutPemberiInfo(pemberiInfoTextField.getText());
                if(getSelected(hasilKunjunganButtonGroup)!=null){
                        String temp = getSelected(hasilKunjunganButtonGroup).getText();
                        ruta.setHasilKunjungan(temp);
                        if(temp.equalsIgnoreCase("Menolak") || temp.equalsIgnoreCase("Tidak dapat ditemui")){
                           
                                JTextField jumlahART=new JTextField();
                                JTextField jumlahArtSepuluhKeatas=new JTextField();
                                JPanel modal = new JPanel(new GridLayout(0, 1));
                                modal.add(new JLabel("Jumlah anggota rumah tangga:"));
                                modal.add(jumlahART);
                                modal.add(new JLabel("Jumlah anggota rumah tangga diatas 10 tahun:"));
                                modal.add(jumlahArtSepuluhKeatas);
                                int result = JOptionPane.showConfirmDialog(this, modal,"Ringkasan",
                                            JOptionPane.CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
                                if(result == JOptionPane.OK_OPTION){
                                        ringkasan = new Ringkasan();
                                        ringkasan.setJumlahART(Integer.parseInt(jumlahART.getText()));
                                        ringkasan.setJumlahARTSepuluhKeatas(Integer.parseInt(jumlahArtSepuluhKeatas.getText()));
                                        ruta.setRingkasan(ringkasan);
                                        mainScrollPane.setViewportView(new KeteranganPetugasPanel(mainScrollPane,ruta));
                                    }
                            }else{
                                    mainScrollPane.setViewportView(new KeteranganPetugasPanel(mainScrollPane, ruta));
                        }
                }
        
    }//GEN-LAST:event_nextButtonPanelMouseClicked

    private void nextButtonPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonPanelMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nextButtonPanelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton berhasilRadioButton;
    private javax.swing.JTextField desaTextField;
    private javax.swing.ButtonGroup hasilKunjunganButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel judulAPanel1;
    private javax.swing.JTextField kabKotaTextField;
    private javax.swing.JTextField kecamatanTextField;
    private javax.swing.ButtonGroup klasifikasiButtonGroup;
    private javax.swing.JTextField namaKaRuTaTextField;
    private javax.swing.JPanel nextButtonPanel;
    private javax.swing.JTextField nomorBSTextField;
    private javax.swing.JTextField nomorKodeSampleTextField;
    private javax.swing.JTextField nomorRutaSampleTextField;
    private javax.swing.JRadioButton pedesaanRadioButton;
    private javax.swing.JTextField pemberiInfoTextField;
    private javax.swing.JRadioButton perkotaanRadioButton;
    private javax.swing.JTextField provinsiTextField;
    private javax.swing.JTextField provinsiTextField6;
    private javax.swing.JRadioButton tidakKetemuRadioButton;
    private javax.swing.JRadioButton tolakRadioButton;
    // End of variables declaration//GEN-END:variables
}
